Repository magento/magento2, pull requests merged in 2018-05, with the labels that each got.

#14820 Duplicate Order Confirmation Emails for PayPal Express checkout order
  app/code/Magento/Paypal/Model/Express/Checkout.php
Labels: 2.2-develop, Partner: Rocket Web, accept, partners-contribution

#14904 FIX for issue#14869 - Wrong price at backend after update
  app/code/Magento/Quote/Model/ResourceModel/Quote/Item/Collection.php
Labels: 2.2-develop, Partner: MageSpecialist, accept, bugfix, partners-contribution

#14928 Removed extra close tag
  app/code/Magento/Review/view/frontend/templates/view.phtml
Labels: 2.2-develop, accept

#14922 [Backport] Customer observer name typo fix
  app/code/Magento/Customer/etc/events.xml
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#14886 Fixed issue products grid operations in admin cart price rule edit page for user which has no access to CatalogRule module
  app/code/Magento/CatalogRule/Block/Adminhtml/Promo/Widget/Chooser/Sku.php
Labels: 2.2-develop, Partner: Comwrap, accept, partners-contribution

#14940 [Backport] Fix faulty admin spinner animation
  app/design/adminhtml/Magento/backend/web/css/source/variables/_spinner.less
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#14757 Preserve user group id when using /V1/customers/:customerId (PUT)
  app/code/Magento/Customer/Model/ResourceModel/CustomerRepository.php
  app/code/Magento/Customer/Test/Unit/Model/ResourceModel/CustomerRepositoryTest.php
Labels: 2.1-develop, accept

#14874 Fix infinite checkout loader when some script wasn't loaded correctly because of network error
  lib/web/mage/requirejs/resolver.js
Labels: 2.2-develop, accept

#14923 Move customer.account.dashboard.info.extra block to contact information
  app/code/Magento/Customer/view/frontend/templates/account/dashboard/info.phtml
Labels: 2.2-develop, Partner: H&O, accept, partners-contribution

#14939 Renamed "Add Block Names to Hints" config setting to represent what it actually does
  app/code/Magento/Backend/etc/adminhtml/system.xml
Labels: 2.2-develop, accept

#14957 Move customer.account.dashboard.info.extra block to contact information
  app/code/Magento/Customer/view/frontend/templates/account/dashboard/info.phtml
Labels: 2.3-develop, Partner: H&O, accept, partners-contribution, port-to-2.3

#14610 CSV files: added possibility to select PHP input file mode
  lib/internal/Magento/Framework/File/Csv.php
Labels: 2.3-develop, accept

#15015 Fix typo in less button definition
  lib/web/css/source/lib/_buttons.less
Labels: 2.2-develop, accept

#15018 chore: upgrade Node.js to 8
  .travis.yml
Labels: 2.2-develop, accept

#15025 [Backport] Minicart should require dropdownDialog
  app/code/Magento/Checkout/view/frontend/web/js/view/minicart.js
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15033 [Forwardport] chore: upgrade Node.js to 8
  .travis.yml
Labels: 2.3-develop, accept

#15002 small optimization in if-condition
  app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper/AttributeFilter.php
Labels: 2.2-develop, accept

#15016 chore: checkout last 5 commits
  .travis.yml
Labels: 2.2-develop, accept

#15017 chore: use random_int() in some places
  app/code/Magento/Backend/Block/Widget/Grid/Column/Renderer/Massaction.php
  app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php
  app/code/Magento/SalesRule/Model/Coupon/Codegenerator.php
  app/code/Magento/SalesRule/Model/Rule.php
  lib/internal/Magento/Framework/Encryption/Crypt.php
  lib/internal/Magento/Framework/Setup/BackendFrontnameGenerator.php
  lib/internal/Magento/Framework/Webapi/ErrorProcessor.php
  pub/errors/processor.php
  setup/src/Magento/Setup/Model/Address/AddressDataGenerator.php
  setup/src/Magento/Setup/Model/DataGenerator.php
  setup/src/Magento/Setup/Model/Description/DescriptionGenerator.php
  setup/src/Magento/Setup/Model/Description/DescriptionParagraphGenerator.php
  setup/src/Magento/Setup/Model/Description/DescriptionSentenceGenerator.php
  setup/src/Magento/Setup/Model/Description/Mixin/BoldMixin.php
  setup/src/Magento/Setup/Model/Description/Mixin/Helper/RandomWordSelector.php
  setup/src/Magento/Setup/Model/Description/Mixin/ItalicMixin.php
  setup/src/Magento/Setup/Model/Description/Mixin/SpanMixin.php
  setup/src/Magento/Setup/Model/Dictionary.php
Labels: 2.2-develop, accept

#15022 [2.3-develop] [ForwardPort] Port of #15020 Update Gallery Template to handle boolean config Variables
  app/code/Magento/Catalog/view/frontend/templates/product/view/gallery.phtml
Labels: 2.3-develop, accept

#15050 [Forwardport] Duplicate Order Confirmation Emails for PayPal Express checkout
  app/code/Magento/Paypal/Model/Express/Checkout.php
Labels: 2.3-develop, Partner: Atwix, accept, forwardport, partners-contribution

#15051 [Forwardport] Add statement to 'beforeSave' method to allow app:config:import
  app/code/Magento/Braintree/Model/Adminhtml/System/Config/CountryCreditCard.php
Labels: 2.3-develop, Partner: Atwix, accept, forwardport, partners-contribution

#15069 [Forwardport] Code cleanup, add more visibility
  app/code/Magento/Rule/Model/Condition/AbstractCondition.php
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15073 [Forwardport] Changed return type of addToCartPostParams to array
  app/code/Magento/Catalog/Block/Product/ListProduct.php
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15075 [Forwardport] Removed extra spaces from language file
  app/code/Magento/CatalogInventory/i18n/en_US.csv
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15078 [Forwardport] Removed extra close tag
  app/code/Magento/Review/view/frontend/templates/view.phtml
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15081 [Forwardport] use "Module_Name::template/path" format instead of using template/path i…
  app/code/Magento/Review/Block/Product/ReviewRenderer.php
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15020 [2.2-develop] Update Gallery Template to handle boolean config Variables
  app/code/Magento/Catalog/view/frontend/templates/product/view/gallery.phtml
Labels: 2.2-develop, accept

#15032 [TASK] Fix overriding of payment methods in getPaymentMethodList
  app/code/Magento/Payment/Helper/Data.php
Labels: 2.2-develop, Partner: Netz98, accept, partners-contribution

#15053 Fixes typo
  app/code/Magento/CatalogSearch/Block/Advanced/Form.php
Labels: 2.2-develop, accept

#15067 fixed documentation about viewModels. The key in xml should be view_m…
  app/code/Magento/Backend/Block/Template.php
Labels: 2.2-develop, accept

#15138 [Backport] Add concrete type hints for product and category resources
  app/code/Magento/Catalog/Model/Category.php
  app/code/Magento/Catalog/Model/Product.php
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15146 [Backport] Fix typo in input type variable name
  app/code/Magento/CatalogSearch/Block/Advanced/Form.php
Labels: 2.1-develop, Partner: Atwix, accept, partners-contribution

#14428 Fix \Magento\Checkout\Controller\Index\Index::isSecureRequest method to take care of current request being secure and also from referer, as stated in phpdoc block
  app/code/Magento/Checkout/Controller/Index/Index.php
  app/code/Magento/Checkout/Test/Unit/Controller/Index/IndexTest.php
Labels: 2.2-develop, Partner: Interactiv4, accept, partners-contribution

#15091 [Backport] Fix infinite checkout loader on a script error
  lib/web/mage/requirejs/resolver.js
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15101 [Backport] FIX for issue#14855 - Adding an * to do a customer search
  lib/internal/Magento/Framework/View/Element/UiComponent/DataProvider/FulltextFilter.php
Labels: 2.1-develop, Partner: Atwix, accept, partners-contribution

#15104 [Backport] Change 'Update'-button visibility on change qty event
  app/code/Magento/Checkout/view/frontend/web/js/sidebar.js
Labels: 2.1-develop, Partner: Atwix, accept, partners-contribution

#14429 [ForwardPort 2.3-develop] Fix \Magento\Checkout\Controller\Index\Index::isSecureRequest method to take care of current request being secure and also from referer, as stated in phpdoc block
  app/code/Magento/Checkout/Controller/Index/Index.php
  app/code/Magento/Checkout/Test/Unit/Controller/Index/IndexTest.php
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15070 [Forwardport] Duplicate Order Confirmation Emails for PayPal Express checkout order
  app/code/Magento/Paypal/Model/Express/Checkout.php
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15071 [Forwardport] Add statement to 'beforeSave' method to allow app:config:import
  app/code/Magento/Braintree/Model/Adminhtml/System/Config/CountryCreditCard.php
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15123 [Forwardport] small optimization in if-condition
  app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper/AttributeFilter.php
Labels: 2.3-develop, accept

#15143 [Forwardport] chore: checkout last 5 commits
  .travis.yml
Labels: 2.3-develop, accept

#15154 [Forwardport] Fixed documentation about viewModels
  app/code/Magento/Backend/Block/Template.php
Labels: 2.3-develop, Partner: Atwix, accept, partners-contribution

#15072 [Forwardport] Fix infinite checkout loader when some script wasn't loaded correctly because of network error
  lib/web/mage/requirejs/resolver.js
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15074 [Forwardport] Fixed issue products grid operations in admin cart price rule edit page for user which has no access to CatalogRule module
  app/code/Magento/CatalogRule/Block/Adminhtml/Promo/Widget/Chooser/Sku.php
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15077 [Forwardport] FIX for issue#14855 - Adding an * to do a customer search
  lib/internal/Magento/Framework/View/Element/UiComponent/DataProvider/FulltextFilter.php
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15079 [Forwardport] Change 'Update'-button visibility on change qty event.
  app/code/Magento/Checkout/view/frontend/web/js/sidebar.js
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15080 [Forwardport] Renamed "Add Block Names to Hints" config setting to represent what it actually does
  app/code/Magento/Backend/etc/adminhtml/system.xml
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15134 [Forwardport] [TASK] Fix overriding of payment methods in getPaymentMethodList
  app/code/Magento/Payment/Helper/Data.php
Labels: 2.3-develop, accept

#15142 [Forwardport] Changed the length of the remote_ip field to store ipv6 addresses
  app/code/Magento/Quote/etc/db_schema.xml
  app/code/Magento/Sales/etc/db_schema.xml
Labels: 2.3-develop, Partner: Atwix, accept, partners-contribution

#15129 Add missing false-check to the ConfiguredRegularPrice price-model
  app/code/Magento/Catalog/Pricing/Price/ConfiguredRegularPrice.php
Labels: 2.2-develop, Partner: Inviqa, accept, partners-contribution

#15136 [Backport] Add concrete type hints for product and category resources
  app/code/Magento/Catalog/Model/Category.php
  app/code/Magento/Catalog/Model/Product.php
Labels: 2.2-develop, Partner: Atwix, accept, backport, partners-contribution

#15162 Fixed js error when product has double quote in its name
  app/code/Magento/Catalog/view/frontend/templates/product/breadcrumbs.phtml
Labels: 2.2-develop, accept

#15173 Removed unused class declaration & code in comment
  app/code/Magento/Review/view/frontend/templates/redirect.phtml
  app/code/Magento/Version/Controller/Index/Index.php
Labels: 2.2-develop, accept

#15094 [Backport] Duplicate Order Confirmation Emails for PayPal Express checkout order
  app/code/Magento/Paypal/Model/Express/Checkout.php
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15103 [Backport] Removed extra close tag
  app/code/Magento/Review/view/frontend/templates/view.phtml
Labels: 2.1-develop, Partner: Atwix, accept, partners-contribution

#15169 Swatches module file was missing in 2.1
  app/code/Magento/Swatches/etc/acl.xml
Labels: 2.1-develop, accept

#15183 [Backport] Corrected param in docblock
  app/code/Magento/OfflineShipping/Block/Adminhtml/Form/Field/Export.php
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15184 [Backport] Removed unused class declaration and code
  app/code/Magento/Review/view/frontend/templates/redirect.phtml
  app/code/Magento/Version/Controller/Index/Index.php
Labels: 2.1-develop, Partner: Atwix, accept, partners-contribution

#15174 Restored app:config:status command after it was accidentally removed.
  app/code/Magento/Deploy/etc/di.xml
Labels: 2.2-develop, accept

#12324 Simplified \Magento\Framework\Reflection\TypeProcessor
  lib/internal/Magento/Framework/Reflection/Test/Unit/DataObject.php
  lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest.php
  lib/internal/Magento/Framework/Reflection/TypeProcessor.php
Labels: 2.2-develop, accept, improvement

#13185 Fix negative basket total due to shipping tax residue
  app/code/Magento/Tax/Model/Sales/Total/Quote/Tax.php
Labels: 2.2-develop, Partner: Ampersand, partners-contribution

#15128 [Forwardport] chore: use random_int() in some places
  app/code/Magento/Backend/Block/Widget/Grid/Column/Renderer/Massaction.php
  app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php
  app/code/Magento/SalesRule/Model/Coupon/Codegenerator.php
  app/code/Magento/SalesRule/Model/Rule.php
  lib/internal/Magento/Framework/Encryption/Crypt.php
  lib/internal/Magento/Framework/Setup/BackendFrontnameGenerator.php
  lib/internal/Magento/Framework/Webapi/ErrorProcessor.php
  pub/errors/processor.php
  setup/src/Magento/Setup/Model/Address/AddressDataGenerator.php
  setup/src/Magento/Setup/Model/DataGenerator.php
  setup/src/Magento/Setup/Model/Description/DescriptionGenerator.php
  setup/src/Magento/Setup/Model/Description/DescriptionParagraphGenerator.php
  setup/src/Magento/Setup/Model/Description/DescriptionSentenceGenerator.php
  setup/src/Magento/Setup/Model/Description/Mixin/BoldMixin.php
  setup/src/Magento/Setup/Model/Description/Mixin/Helper/RandomWordSelector.php
  setup/src/Magento/Setup/Model/Description/Mixin/ItalicMixin.php
  setup/src/Magento/Setup/Model/Description/Mixin/SpanMixin.php
  setup/src/Magento/Setup/Model/Dictionary.php
Labels: 2.3-develop, accept

#15203 [Backport 2.1] Fix for displaying a negative price for a custom option
  app/code/Magento/Catalog/view/base/web/js/price-options.js
Labels: 2.1-develop, accept

#15240 Remove unused namespace from ui export
  app/code/Magento/Ui/Model/Export/ConvertToCsv.php
  app/code/Magento/Ui/Model/Export/ConvertToXml.php
Labels: 2.1-develop, accept

#14614 Add Parent Item to order item in repository
  app/code/Magento/Sales/Model/Order/ItemRepository.php
  dev/tests/integration/testsuite/Magento/Sales/Model/Order/ItemRepositoryTest.php
Labels: 2.2-develop, Partner: H&O, Partner: Reach Digital, accept, partners-contribution

#15172 7399-clickableOverlay-less-fix - added pointer-events rule to .modal-…
  app/design/frontend/Magento/blank/web/css/source/components/_modals_extend.less
  app/design/frontend/Magento/luma/web/css/source/components/_modals_extend.less
Labels: 2.2-develop, accept, fra-rz-cd

#15197 Fix Magento_ImportExport not supporting unicode characters in column names
  app/code/Magento/ImportExport/Model/Import/AbstractEntity.php
  app/code/Magento/ImportExport/Model/Import/Entity/AbstractEntity.php
Labels: 2.2-develop, Import/Export, accept

#15202 [Backport 2.2] Fix for displaying a negative price for a custom option.
  app/code/Magento/Catalog/view/base/web/js/price-options.js
Labels: 2.2-develop, accept

#15221 [Backport] Translate action Label
  app/code/Magento/Config/view/adminhtml/templates/system/config/form/field/array.phtml
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15222 [Backport] Fixed datepicker problem when using non en-US locale.
  lib/web/mage/utils/misc.js
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15137 fix: do not forcefully set area in template if it is already set, fixes #14968, fixes #13530
  app/code/Magento/Theme/Test/Unit/Model/Design/Config/ValidatorTest.php
Labels: 2.2-develop, accept

#15256 Fixed typo in method name
  lib/internal/Magento/Framework/App/Request/Http.php
Labels: 2.2-develop, accept

#15159 [Backport] Default schedule config for sitemap_generate job added
  app/code/Magento/Sitemap/Model/Observer.php
  app/code/Magento/Sitemap/etc/config.xml
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15082 [Forwardport] Fixed Overlay Problems
  app/design/frontend/Magento/luma/Magento_Theme/web/css/source/_module.less
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15168 [Port 2.3-develop] Add parent item to order item
  app/code/Magento/Sales/Model/Order/ItemRepository.php
  dev/tests/integration/testsuite/Magento/Sales/Model/Order/ItemRepositoryTest.php
Labels: 2.3-develop, Partner: H&O, Partner: Reach Digital, accept, partners-contribution, port-to-2.3

#15185 [Forwardport] Removed unused class declaration and code
  app/code/Magento/Review/view/frontend/templates/redirect.phtml
  app/code/Magento/Version/Controller/Index/Index.php
Labels: 2.3-develop, Partner: Atwix, accept, partners-contribution

#15186 [Forwardport] Fixed js error when product has double quote in its name
  app/code/Magento/Catalog/view/frontend/templates/product/breadcrumbs.phtml
Labels: 2.3-develop, accept

#15198 MSI: Remove MultiDimensionalIndexer from framework
  app/etc/di.xml
  lib/internal/Magento/Framework/MultiDimensionalIndexer/Alias.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/AliasFactory.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/Dimension.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/DimensionFactory.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/IndexHandlerInterface.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/IndexName.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/IndexNameBuilder.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/IndexNameResolver.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/IndexNameResolverInterface.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/IndexStructureInterface.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/IndexTableSwitcher.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/IndexTableSwitcherInterface.php
  lib/internal/Magento/Framework/MultiDimensionalIndexer/README.md
  lib/internal/Magento/Framework/Test/Unit/MultiDimensionalIndexer/IndexTableSwitcherTest.php
Labels: 2.3-develop, accept

#15235 [Backport] Fixed double space typo
  app/code/Magento/Paypal/i18n/en_US.csv
  app/code/Magento/Paypal/view/adminhtml/templates/system/config/payflowlink/advanced.phtml
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15237 [Backport] Changed constructor typo in Javascript class
  app/code/Magento/Ui/view/base/web/js/lib/core/class.js
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15233 [Backport] Fix typo in design rule hint message
  app/code/Magento/Backend/view/adminhtml/web/template/dynamic-rows/grid.html
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15234 [Backport] Add missing translations in Magento_UI
  app/code/Magento/Ui/i18n/en_US.csv
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15238 [Backport] Fixed php notice when invalid ui_component config is used
  lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15194 Move buttons definition to separate file
  app/code/Magento/Ui/view/base/web/js/form/adapter.js
  app/code/Magento/Ui/view/base/web/js/form/adapter/buttons.js
Labels: 2.2-develop, accept

#15262 Fix \Magento\Customer\Model\Customer\NotificationStorage class
  app/code/Magento/Customer/Model/Customer/NotificationStorage.php
Labels: 2.2-develop, Partner: Interactiv4, accept, partners-contribution

#15038 [2.1-develop][Backport] Transport variable can not be altered in email_invoice_set_template_vars_before Event
  app/code/Magento/Sales/Model/Order/Email/Sender/OrderSender.php
Labels: 2.1-develop, accept

#15058 Add 'const' type support to layout arguments
  app/code/Magento/Ui/etc/di.xml
  lib/internal/Magento/Framework/View/Layout/etc/layout_merged.xsd
  lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd
Labels: 2.2-develop, accept

#15269 Fix typo in Image::open exception message
  lib/internal/Magento/Framework/Image.php
Labels: 2.2-develop, accept

#15282 [fix] typo in private method name getUniq[ue]ImageIndex
  app/code/Magento/Catalog/Console/Command/ImagesResizeCommand.php
Labels: 2.2-develop, accept

#15291 [Backport] Fix typo in database column comment
  app/code/Magento/Catalog/Setup/InstallSchema.php
Labels: 2.2-develop, Partner: Atwix, accept, backport, partners-contribution

#15298 [Backport] Fix typos in variable names
  dev/tests/integration/testsuite/Magento/AdminNotification/_files/notifications.php
  dev/tests/integration/testsuite/Magento/Framework/Mview/View/ChangelogTest.php
Labels: 2.1-develop, Partner: Atwix, accept, partners-contribution

#15299 [Backport] Fix typos in PHPDocs and comments
  dev/tests/functional/lib/Magento/Mtf/Client/Element/SimplifiedselectElement.php
  dev/tests/functional/lib/Magento/Mtf/Client/Element/SwitcherElement.php
  dev/tests/functional/tests/app/Magento/Catalog/Test/Block/Adminhtml/Product/Edit/Section/Attributes/Search.php
  dev/tests/functional/tests/app/Magento/Catalog/Test/Constraint/AssertProductAttributeIsHtmlAllowed.php
  dev/tests/functional/tests/app/Magento/Catalog/Test/Fixture/Product/TierPrice.php
  dev/tests/functional/tests/app/Magento/Catalog/Test/Fixture/Product/WebsiteIds.php
  dev/tests/functional/tests/app/Magento/Checkout/Test/Constraint/AssertBillingAddressSameAsShippingCheckbox.php
  dev/tests/functional/tests/app/Magento/ConfigurableProduct/Test/Constraint/AssertProductTierPriceOnProductPage.php
  dev/tests/functional/tests/app/Magento/Customer/Test/TestCase/AbstractApplyVatIdTest.php
  dev/tests/functional/tests/app/Magento/Integration/Test/TestCase/ReAuthorizeTokensIntegrationEntityTest.php
  dev/tests/functional/tests/app/Magento/Sales/Test/Block/Adminhtml/Order/Create/CustomerActivities/Sidebar.php
  dev/tests/functional/tests/app/Magento/Sales/Test/TestCase/CancelCreatedOrderTest.php
  dev/tests/functional/tests/app/Magento/Sales/Test/TestCase/CreateCustomOrderStatusEntityTest.php
  dev/tests/functional/tests/app/Magento/SalesRule/Test/Constraint/AssertCartPriceRuleSuccessDeleteMessage.php
  dev/tests/functional/tests/app/Magento/Theme/Test/Block/Html/Footer.php
  dev/tests/functional/tests/app/Magento/Ui/Test/Block/Adminhtml/DataGrid.php
  dev/tests/functional/tests/app/Magento/Ui/Test/Block/Adminhtml/Modal.php
  dev/tests/functional/tests/app/Magento/Ui/Test/TestCase/GridFullTextSearchTest.php
  dev/tests/functional/tests/app/Magento/UrlRewrite/Test/Block/Adminhtml/Catalog/Edit/UrlRewriteForm.php
  dev/tests/functional/tests/app/Magento/Widget/Test/Constraint/AssertWidgetCmsPageLink.php
  dev/tests/integration/framework/Magento/TestFramework/Db/AbstractDb.php
  dev/tests/integration/framework/Magento/TestFramework/Db/Mysql.php
  dev/tests/integration/framework/Magento/TestFramework/TestCase/AbstractConfigFiles.php
  dev/tests/integration/testsuite/Magento/Catalog/Model/Product/TypeTest.php
  dev/tests/integration/testsuite/Magento/CatalogImportExport/_files/product_export_with_product_links_data.php
  dev/tests/integration/testsuite/Magento/Framework/Data/Form/Element/FieldsetTest.php
  dev/tests/integration/testsuite/Magento/Search/Model/SearchEngine/ConfigTest.php
  dev/tests/static/framework/Magento/Sniffs/Less/ZeroUnitsSniff.php
  lib/internal/Magento/Framework/App/DeploymentConfig.php
Labels: 2.1-develop, Partner: Atwix, accept, partners-contribution

#15324 [Backport] Added hyphenation cutting edge to cutting-edge
  README.md
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15363 [Backport] Alignment Array assignment
  app/code/Magento/Store/Setup/InstallSchema.php
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15375 [Backport] Fix typo in securityCheckers array
  app/code/Magento/Security/etc/adminhtml/di.xml
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15377 [Backport] Typo in SSL port number
  pub/errors/processor.php
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15380 [Backport] Fix incorrect phpdoc return type
  app/code/Magento/Catalog/Model/ResourceModel/Collection/AbstractCollection.php
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15385 [Backport] Unused variable removed
  lib/web/css/source/lib/variables/_typography.less
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#14395 Fix for not working LESS extends
  app/design/frontend/Magento/blank/Magento_Checkout/web/css/source/module/checkout/_tooltip.less
  app/design/frontend/Magento/blank/Magento_Sales/web/css/source/_module.less
  app/design/frontend/Magento/blank/web/css/source/_extends.less
  app/design/frontend/Magento/blank/web/css/source/components/_modals_extend.less
  app/design/frontend/Magento/luma/web/css/source/_extends.less
  app/design/frontend/Magento/luma/web/css/source/components/_modals_extend.less
Labels: 2.3-develop, Partner: SNOW.DOG, accept, partners-contribution

#14975 Fix for displaying a negative price for a custom option.
  app/code/Magento/Catalog/view/base/web/js/price-options.js
Labels: 2.3-develop, accept

#15263 [Forwardport] Fix \Magento\Customer\Model\Customer\NotificationStorage class
  app/code/Magento/Customer/Model/Customer/NotificationStorage.php
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#15274 [Forwardport] Fixed typo in method name
  lib/internal/Magento/Framework/App/Request/Http.php
Labels: 2.3-develop, Partner: Atwix, accept, partners-contribution

#15039 [2.3-develop][Forwardport] Transport variable can not be altered in email_invoice_set_template_vars_before Event
  app/code/Magento/Sales/Model/Order/Email/Sender/OrderSender.php
Labels: 2.3-develop, accept

#15394 [Backport] Remove non-existing argument
  app/code/Magento/Translation/Block/Html/Head/Config.php
Labels: 2.1-develop, Partner: Atwix, accept, partners-contribution

#15396 [Backport] Fixed typo mistake in function comment
  app/code/Magento/Theme/Model/Config.php
Labels: 2.1-develop, Partner: Atwix, accept, partners-contribution

#15387 ADHOC: update the contribution templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 2.3-develop, accept

#15395 [Forwardport] Removed non-existing argument
  app/code/Magento/Translation/Block/Html/Head/Config.php
Labels: 2.3-develop, Partner: Atwix, accept, partners-contribution

#15397 [Forwardport] Fixed typo mistake in function comment
  app/code/Magento/Theme/Model/Config.php
Labels: 2.3-develop, Partner: Atwix, accept, partners-contribution

#15412 [Backport-2.1] Fixed typo in MagentoUi abstract.js
  app/code/Magento/Ui/view/base/web/js/form/element/abstract.js
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution, typo

#15265 declare var to fix scope error
  app/code/Magento/Catalog/view/adminhtml/web/js/category-checkbox-tree.js
Labels: 2.2-develop, accept

#15331 set alignment purchase order form and place order button
  app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/checkout/_payments.less
Labels: 2.2-develop, Partner: Wagento, accept, dmcdindia, partners-contribution

#15346 Function is unnecessarily called multiple time
  app/code/Magento/CurrencySymbol/view/adminhtml/templates/grid.phtml
Labels: 2.2-develop, accept, dmcdindia

#15350 15319 : misleading data-container in product list
  app/code/Magento/Analytics/etc/adminhtml/system.xml
Labels: 2.2-develop, accept, dmcdindia

#15351 Refactor javascript code of button split widget
  app/code/Magento/Backend/view/adminhtml/templates/widget/button/split.phtml
Labels: 2.2-develop, accept, dmcdindia

#15362 Removed duplicate line and added comment on variable
  app/code/Magento/Sales/Block/Adminhtml/Order/Create/Totals/Discount.php
Labels: 2.2-develop, Sales, accept, dmcdindia, improvement

#15411 [Backport-2.2] Fixed abstract.js typo
  app/code/Magento/Ui/view/base/web/js/form/element/abstract.js
Labels: 2.2-develop, Partner: Atwix, accept, backport, partners-contribution, typo

#15089 Fix unnecessary recalculation of product list pricing
  app/code/Magento/Tax/Model/Config.php
Labels: 2.2-develop, Partner: H&O, Partner: Reach Digital, accept, partners-contribution

#15247 ISSUE-14747 Newsletter subscription confirmation message does not dis…
  app/code/Magento/Newsletter/Controller/Subscriber/Confirm.php
Labels: 2.2-develop, accept

#15275 [fix] typo in method name _exportAddress[s]es
  app/code/Magento/Paypal/Model/Api/Nvp.php
Labels: 2.2-develop, accept

#15332 #14063 - Wrong invoice prefix in multistore setup due to default stor…
  app/code/Magento/Sales/Model/ResourceModel/EntityAbstract.php
Labels: 2.2-develop, Partner: Wagento, accept, dmcdindia, partners-contribution

#15336 #12820 - Wrong annotation in _toOptionArray - magento/framework/Data/…
  lib/internal/Magento/Framework/Data/Collection/AbstractDb.php
Labels: 2.2-develop, Partner: Wagento, accept, dmcdindia, partners-contribution

#15347 Fixed breadcrumb quote issue in product page #15037
  app/code/Magento/Catalog/view/frontend/templates/product/breadcrumbs.phtml
Labels: 2.2-develop, accept, dmcdindia

#15372 Fixed Purchased Order Form button should visible properly
  app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/checkout/_payments.less
Labels: 2.2-develop, accept, dmcdindia

#15370 Fixed typo in MagentoUi abstract.js
  app/code/Magento/Ui/view/base/web/js/form/element/abstract.js
Labels: 2.3-develop, Partner: Atwix, accept, partners-contribution, typo

#15353 Responsive Design Footers bottom of screen on mobile devices #15118
  app/design/frontend/Magento/luma/Magento_Theme/web/css/source/_module.less
Labels: 2.2-develop, Partner: Wagento, accept, dmcdindia, partners-contribution

#15398 Fixed set template syntax issue
  app/code/Magento/Backend/Block/Dashboard.php
  app/code/Magento/Backend/Block/Dashboard/Graph.php
  app/code/Magento/Backend/Block/Dashboard/Grid.php
  app/code/Magento/Backend/Block/Dashboard/Sales.php
  app/code/Magento/Backend/Block/Dashboard/Totals.php
  app/code/Magento/Backend/Block/Page/Copyright.php
  app/code/Magento/Backend/Block/Page/Footer.php
  app/code/Magento/Backend/Block/Page/Header.php
  app/code/Magento/Backend/Block/Store/Switcher/Form/Renderer/Fieldset.php
  app/code/Magento/Backend/Block/Store/Switcher/Form/Renderer/Fieldset/Element.php
Labels: 2.2-develop

#15431 typo correction
  app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php
Labels: 2.2-develop, accept

#15318 [Backport] Allow configuring min and max dates for date picker component
  lib/internal/Magento/Framework/Data/Form/Element/Date.php
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15392 [Backport] Add 'const' type support to layout arguments
  app/code/Magento/Ui/etc/di.xml
  lib/internal/Magento/Framework/View/Layout/etc/layout_merged.xsd
  lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd
Labels: 2.1-develop, accept

#15407 [Backport] Fix to allow use decimals less then 1 in subproducts qty
  lib/web/mage/validation/validation.js
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#15436 [Backport] Removed redundant else statement
  app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php
Labels: 2.1-develop, Import/Export, Partner: Atwix, accept, backport, partners-contribution

#15450 ADHOC: update the contribution templates to include a note on results
  .github/ISSUE_TEMPLATE.md
Labels: 2.3-develop, accept

#15466 [Forwardport] typo correction
  app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php
Labels: 2.3-develop, accept

#15211 Error 500 in Module Manager
  setup/src/Magento/Setup/Model/Grid/Module.php
Labels: 2.2-develop, accept

#15258 [backport] fixes for instant purchase module from #15257
  app/code/Magento/InstantPurchase/Model/InstantPurchaseOption.php
  app/code/Magento/InstantPurchase/Model/InstantPurchaseOptionLoadingFactory.php
  app/code/Magento/InstantPurchase/Model/ShippingMethodChoose/DeferredShippingMethodChooserPool.php
  app/code/Magento/InstantPurchase/PaymentMethodIntegration/IntegrationsManager.php
Labels: 2.2-develop, accept

#15340 Submitting search form (mini) with enter key fires event handlers bound by jquery twice
  app/code/Magento/Search/view/frontend/web/form-mini.js
Labels: 2.2-develop, accept, dmcdindia

#15364 Added language translation for comment tag
  app/code/Magento/Signifyd/etc/adminhtml/system.xml
Labels: 2.2-develop, accept, dmcdindia

#15371 Added language translation in template files
  app/code/Magento/Braintree/view/adminhtml/templates/form/cc.phtml
  app/code/Magento/Multishipping/i18n/en_US.csv
  app/code/Magento/Multishipping/view/frontend/templates/checkout/results.phtml
  app/code/Magento/Multishipping/view/frontend/templates/checkout/success.phtml
  app/code/Magento/Paypal/view/adminhtml/templates/transparent/form.phtml
Labels: 2.2-develop, Shipping, accept, dmcdindia, improvement

#15409 Prevent multiple add-to-cart initializations in case of ajax loaded product listing
  app/code/Magento/Catalog/view/frontend/web/js/catalog-add-to-cart.js
Labels: 2.2-develop, accept

#15421 Updated font-size variable and standardize #ToDo UI
  app/design/adminhtml/Magento/backend/web/app/setup/styles/less/lib/_buttons.less
Labels: 2.2-develop, accept

#15422 Refactor JavsScript for UrlRewrite module edit page
  app/code/Magento/UrlRewrite/view/adminhtml/templates/edit.phtml
  app/code/Magento/UrlRewrite/view/adminhtml/web/js/url-rewrite-validation.js
Labels: 2.2-develop, accept

#15435 [Backport] Removed redundant else statement
  app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php
Labels: 2.2-develop, Import/Export, Partner: Atwix, accept, backport, partners-contribution

#15460 Improvements to the CONTRIBUTING.md document
  .github/CONTRIBUTING.md
Labels: 2.2-develop, accept

#15360 15210-Fixed product tier pricing pagination issue in admin
  app/code/Magento/Ui/view/base/web/js/dynamic-rows/dynamic-rows.js
Labels: 2.3-develop, accept, dmcdindia

#15489 Duplicate array keys
  app/code/Magento/Catalog/Test/Unit/Model/ProductRepositoryTest.php
Labels: 2.3-develop, accept

#15492 Return tag misspelled
  app/code/Magento/ReleaseNotification/Ui/Renderer/NotificationRenderer.php
Labels: 2.3-develop, accept

#15465 [Backport] typo correction
  app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php
Labels: 2.1-develop, accept

#15312 [Fix] forgot to add lowercase conversion on grouped product assignation
  app/code/Magento/GroupedImportExport/Model/Import/Product/Type/Grouped.php
Labels: 2.2-develop, Component: ImportExport, accept

#15416 Moved css from media #TODO
  app/design/frontend/Magento/luma/Magento_Theme/web/css/source/_module.less
Labels: 2.2-develop, accept
