Repository magento/magento2, pull requests merged in 2018-04, with the labels that each got.

#14437 [Forwardport] Disable add to cart button when redirect to cart enabled
  app/code/Magento/Catalog/view/frontend/templates/product/view/addtocart.phtml
Labels: 2.3-develop, accept

#14453 [ForwardPort 2.3-develop] Remove else statements from \Magento\Framework\Session\SessionManager
  lib/internal/Magento/Framework/Session/SessionManager.php
Labels: 2.3-develop, Partner: Interactiv4, accept, partners-contribution

#14481 Parameter update for post method in http client interface
  lib/internal/Magento/Framework/HTTP/ClientInterface.php
Labels: 2.3-develop, Application Framework, accept, improvement

#14293 Moved Google Analytics block code to head tag #8837
  app/code/Magento/GoogleAnalytics/view/frontend/layout/default.xml
  dev/tests/integration/testsuite/Magento/GoogleAnalytics/Block/GaTest.php
Labels: 2.2-develop, accept

#14439 Update process-reviews.js
  app/code/Magento/Review/view/frontend/web/js/process-reviews.js
Labels: 2.2-develop, accept

#14445 [FIX] Simplify ternary operators for catalog module
  app/code/Magento/Catalog/Model/Api/SearchCriteria/CollectionProcessor/FilterProcessor/ProductCategoryFilter.php
  app/code/Magento/Catalog/Model/CategoryRepository.php
  app/code/Magento/Catalog/Model/Product.php
  app/code/Magento/Catalog/Model/Product/Option/Type/File.php
  app/code/Magento/Catalog/Model/Product/ProductList/Toolbar.php
  app/code/Magento/Catalog/Model/Product/Type/Price.php
  app/code/Magento/Catalog/Model/ProductRepository.php
  app/code/Magento/Catalog/Test/Unit/Model/Api/SearchCriteria/CollectionProcessor/FilterProcessor/ProductCategoryFilterTest.php
Labels: 2.2-develop, Catalog, Partner: Vaimo, accept, partners-contribution

#14452 Remove else statements from \Magento\Framework\Session\SessionManager
  lib/internal/Magento/Framework/Session/SessionManager.php
Labels: 2.2-develop, Partner: Interactiv4, accept, partners-contribution

#14455 Fix button color on hover in email template
  app/code/Magento/Review/i18n/en_US.csv
Labels: 2.2-develop, Frontend, Reproduced on 2.1.x, Reproduced on 2.3.x, accept

#14473 Added spanish Bolivia locale to allowedLocales list
  lib/internal/Magento/Framework/Locale/Config.php
Labels: 2.2-develop, Partner: Wagento, accept, partners-contribution

#14497 [backport] fix for button color in email template
  app/design/frontend/Magento/blank/web/css/source/_email-base.less
Labels: 2.1-develop, accept, backport

#13808 [Backport 2.2] Configurable product price options by store
  app/code/Magento/ConfigurableProduct/Pricing/Price/LowestPriceOptionsProvider.php
  app/code/Magento/ConfigurableProduct/Test/Unit/Pricing/Price/LowestPriceOptionsProviderTest.php
Labels: 2.2-develop, accept, backport

#14360 Fix issue #13010. Check if product is assigned to current website.
  app/code/Magento/Review/Controller/Product.php
  app/code/Magento/Review/Test/Unit/Controller/Product/PostTest.php
Labels: 2.2-develop, accept

#14348 [Backport 2.1] Add json and xml support to the post method in socket client
  lib/internal/Magento/Framework/HTTP/Client/Socket.php
Labels: 2.1-develop, Application Framework, TECH, accept, advanced, backport, distributed-cd, improvement

#14479 [Backport 2.1] Configurable product price options by store
  app/code/Magento/ConfigurableProduct/Pricing/Price/LowestPriceOptionsProvider.php
Labels: 2.1-develop, accept, backport

#14501 [Forwardport] Added spanish Bolivia locale to allowedLocales list
  lib/internal/Magento/Framework/Locale/Config.php
Labels: 2.3-develop, accept

#14503 [Forwardport] Update process-reviews.js
  app/code/Magento/Review/view/frontend/web/js/process-reviews.js
Labels: 2.3-develop, accept

#14506 [Forwardport] [FIX] Simplify ternary operators for catalog module
  app/code/Magento/Catalog/Model/Api/SearchCriteria/CollectionProcessor/FilterProcessor/ProductCategoryFilter.php
  app/code/Magento/Catalog/Model/CategoryRepository.php
  app/code/Magento/Catalog/Model/Product.php
  app/code/Magento/Catalog/Model/Product/Option/Type/File.php
  app/code/Magento/Catalog/Model/Product/ProductList/Toolbar.php
  app/code/Magento/Catalog/Model/Product/Type/Price.php
  app/code/Magento/Catalog/Model/ProductRepository.php
  app/code/Magento/Catalog/Test/Unit/Model/Api/SearchCriteria/CollectionProcessor/FilterProcessor/ProductCategoryFilterTest.php
Labels: 2.3-develop, accept

#14504 Check if store id is not null instead of empty
  app/code/Magento/Cms/Model/PageRepository.php
Labels: 2.2-develop, accept

#14505 [Backport] Check if store id is not null instead of empty
  app/code/Magento/Cms/Model/PageRepository.php
Labels: 2.1-develop, accept, backport

#13629 Fix translate issue
  lib/internal/Magento/Framework/Translate.php
Labels: 2.2-develop, accept

#13831 Fixed comparison with 0 bug for TableRate shipping carrier
  app/code/Magento/OfflineShipping/Model/ResourceModel/Carrier/Tablerate/RateQuery.php
Labels: 2.2-develop, accept

#14176 Replace the existing headers with the no cache headers
  app/code/Magento/Customer/Controller/Section/Load.php
Labels: 2.2-develop, accept

#14319 6879 - Unable to change country of manufacture default label value
  lib/web/mage/validation.js
Labels: 2.2-develop, accept, bugfix, distributed-cd

#14482 Fix aggregations use statements and return values
  app/code/Magento/Cms/Model/ResourceModel/Block/Grid/Collection.php
  app/code/Magento/Cms/Model/ResourceModel/Page/Grid/Collection.php
  app/code/Magento/Sales/Model/ResourceModel/Grid/Collection.php
Labels: 2.3-develop, accept

#14576 Improve code structure in relation to else / if statements.
  app/code/Magento/AdminNotification/Block/System/Messages/UnreadMessagePopup.php
  app/code/Magento/AdminNotification/Block/Window.php
  app/code/Magento/AdvancedPricingImportExport/Model/Export/AdvancedPricing.php
  app/code/Magento/AdvancedPricingImportExport/Model/Import/AdvancedPricing.php
  app/code/Magento/Analytics/Model/Config/Backend/Enabled.php
  app/code/Magento/Authorization/Model/ResourceModel/Role.php
Labels: 2.3-develop, Partner: Comwrap, accept, partners-contribution

#14552 Allow to configure min and max dates for date picker component
  lib/internal/Magento/Framework/Data/Form/Element/Date.php
Labels: 2.2-develop, Partner: Inviqa, accept, partners-contribution

#14559 Fix for Issue #13950 - Cache issue with configurable products related to currency-conversions
  app/code/Magento/CatalogWidget/Block/Product/ProductsList.php
  app/code/Magento/CatalogWidget/Test/Unit/Block/Product/ProductsListTest.php
Labels: 2.2-develop, Partner: Comwrap, accept, partners-contribution

#14599 Specify the table when adding field to filter
  app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/Option/Collection.php
Labels: 2.2-develop, accept

#14339 Removal of inline translate script block and load a require file.
  app/code/Magento/Translation/Block/Js.php
  app/code/Magento/Translation/view/base/templates/translate.phtml
  lib/web/mage/translate-init.js
Labels: 2.3-develop, accept, distributed-cd

#14353 magento/magento2#13929: Images can't be uploaded using WYSIWYG if media directory is a symlink
  dev/tests/integration/testsuite/Magento/Framework/App/Filesystem/DirectoryResolverTest.php
  lib/internal/Magento/Framework/App/Filesystem/DirectoryResolver.php
Labels: 2.3-develop, Application Framework, accept, bugfix, distributed-cd

#14665 [Backport 2.1 of PR-13802] Mini cart - fix issue in product title with special chars.
  app/code/Magento/Checkout/CustomerData/DefaultItem.php
  app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html
  app/code/Magento/ConfigurableProduct/CustomerData/ConfigurableItem.php
  app/code/Magento/GroupedProduct/CustomerData/GroupedItem.php
Labels: 2.1-develop, accept

#14318 Move polyfill JavaScript code to be included as a remote script from …
  app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml
  app/code/Magento/Theme/view/frontend/templates/js/polyfill.phtml
  lib/web/mage/polyfill.js
Labels: 2.3-develop, accept, distributed-cd

#14636 [Forwardport] magento/magento2#14465 Fix empty changelog tables after MySQL restart.
  lib/internal/Magento/Framework/Mview/View/Changelog.php
Labels: 2.3-develop, accept, on hold

#14661 [Forwardport] Replace the existing headers with the no cache headers
  app/code/Magento/Customer/Controller/Section/Load.php
Labels: 2.3-develop, accept

#14629 Refactor Code for Mass Order Unhold
  app/code/Magento/Sales/Controller/Adminhtml/Order/MassUnhold.php
  app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/MassUnholdTest.php
Labels: 2.2-develop, accept

#14635 [Forwardport] magento/magento2#14465 Fix empty changelog tables after MySQL restart.
  lib/internal/Magento/Framework/Mview/View/Changelog.php
Labels: 2.2-develop, accept

#14668 Added hyphenation, cutting edge to cutting-edge.
  README.md
Labels: 2.2-develop, accept

#14681 [Backport] Fix #13652. Mini cart - fix issue in product title with special chars.
  app/code/Magento/Checkout/CustomerData/DefaultItem.php
  app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html
  app/code/Magento/ConfigurableProduct/CustomerData/ConfigurableItem.php
  app/code/Magento/GroupedProduct/CustomerData/GroupedItem.php
Labels: 2.2-develop, accept

#14688 Translate Action Label
  app/code/Magento/Config/view/adminhtml/templates/system/config/form/field/array.phtml
Labels: 2.2-develop, accept

#14696 [Backport] Eliminate usage of "else" statements
  app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Radio.php
  app/code/Magento/Backend/Block/Widget/Grid/Massaction/AbstractMassaction.php
  app/code/Magento/Backend/Block/Widget/Grid/Massaction/Extended.php
  app/code/Magento/Backend/Controller/Adminhtml/Auth/Login.php
  app/code/Magento/Backend/Controller/Adminhtml/System/Account/Save.php
  app/code/Magento/Backend/Model/Menu/Item.php
  app/code/Magento/Braintree/Test/Unit/Model/Report/BraintreeTransactionStub.php
  app/code/Magento/Bundle/Block/Adminhtml/Sales/Order/Items/Renderer.php
  app/code/Magento/Bundle/Block/Catalog/Product/View/Type/Bundle/Option.php
  app/code/Magento/Bundle/Block/Sales/Order/Items/Renderer.php
  app/code/Magento/Bundle/Model/Plugin/PriceBackend.php
  app/code/Magento/Bundle/Model/Product/Type.php
  app/code/Magento/Bundle/Model/Sales/Order/Pdf/Items/AbstractItems.php
  app/code/Magento/Bundle/Pricing/Adjustment/Calculator.php
  app/code/Magento/Bundle/Pricing/Price/BundleSelectionPrice.php
  app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php
Labels: 2.2-develop, accept

#14695 [Forwardport] Translate Action Label
  app/code/Magento/Config/view/adminhtml/templates/system/config/form/field/array.phtml
Labels: 2.3-develop, accept

#14630 Refactor Mass Order Cancel code to use Interface
  app/code/Magento/Sales/Controller/Adminhtml/Order/MassCancel.php
  app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/MassCancelTest.php
Labels: 2.3-develop, accept

#14683 [Forwardport] Allow to configure min and max dates for date picker component
  lib/internal/Magento/Framework/Data/Form/Element/Date.php
Labels: 2.3-develop, accept

#14673 [Backport] Fix issue #13010. Check if product is assigned to current website
  app/code/Magento/Review/Controller/Product.php
  app/code/Magento/Review/Test/Unit/Controller/Product/PostTest.php
Labels: 2.1-develop, accept

#14471 magento/magento2#14465 Fix empty changelog tables after MySQL restart.
  lib/internal/Magento/Framework/Mview/View/Changelog.php
Labels: 2.1-develop, Partner: ISM eCompany, accept, on hold, partners-contribution

#14714 [Forwardport] 6879 - Unable to change country of manufacture default label value
  lib/web/mage/validation.js
Labels: 2.3-develop, accept

#14652 Eliminate usage of "else" statements
  app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Radio.php
  app/code/Magento/Backend/Block/Widget/Grid/Massaction/AbstractMassaction.php
  app/code/Magento/Backend/Block/Widget/Grid/Massaction/Extended.php
  app/code/Magento/Backend/Controller/Adminhtml/Auth/Login.php
  app/code/Magento/Backend/Controller/Adminhtml/System/Account/Save.php
  app/code/Magento/Backend/Model/Menu/Item.php
  app/code/Magento/Braintree/Test/Unit/Model/Report/BraintreeTransactionStub.php
  app/code/Magento/Bundle/Block/Adminhtml/Sales/Order/Items/Renderer.php
  app/code/Magento/Bundle/Block/Catalog/Product/View/Type/Bundle/Option.php
  app/code/Magento/Bundle/Block/Sales/Order/Items/Renderer.php
  app/code/Magento/Bundle/Model/Plugin/PriceBackend.php
  app/code/Magento/Bundle/Model/Product/Type.php
  app/code/Magento/Bundle/Model/Sales/Order/Pdf/Items/AbstractItems.php
  app/code/Magento/Bundle/Pricing/Adjustment/Calculator.php
  app/code/Magento/Bundle/Pricing/Price/BundleSelectionPrice.php
  app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php
Labels: 2.3-develop, Partner: Comwrap, accept, partners-contribution

#14666 [Forwardport] Fixed 'Non-numeric value' warning on account create/save when DOB field is visible
  lib/internal/Magento/Framework/Data/Form/Filter/Date.php
Labels: 2.3-develop, accept

#14684 [Forwardport] Fix for Issue #13950 - Cache issue with configurable products related to currency-conversions
  app/code/Magento/CatalogWidget/Block/Product/ProductsList.php
  app/code/Magento/CatalogWidget/Test/Unit/Block/Product/ProductsListTest.php
Labels: 2.3-develop, accept

#14338 Fixing wrong sitemap product url #4788
  app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php
Labels: 2.2-develop, Partner: Atwix, accept, distributed-cd, partners-contribution

#14715 #14669 Css class "empty" is always present on minicart dropdown
  app/code/Magento/Checkout/view/frontend/templates/cart/minicart.phtml
Labels: 2.2-develop, accept

#14736 [backport] magento/magento2#14669: Css class "empty" is always present on minicart dropdown
  app/code/Magento/Checkout/view/frontend/templates/cart/minicart.phtml
Labels: 2.1-develop, accept, backport

#14710 added GNU Free Font to be used by sales PDFs
  app/code/Magento/Sales/Model/Order/Pdf/AbstractPdf.php
  app/code/Magento/Sales/Model/Order/Pdf/Items/AbstractItems.php
  lib/internal/GnuFreeFont/FreeSerif.ttf
  lib/internal/GnuFreeFont/FreeSerifBold.ttf
  lib/internal/GnuFreeFont/FreeSerifItalic.ttf
Labels: 2.3-develop, accept

#14737 [forwardport] magento/magento2#14669: Css class "empty" is always present on minicart dropdown
  app/code/Magento/Checkout/view/frontend/templates/cart/minicart.phtml
Labels: 2.3-develop, accept, forwardport

#14676 [Forwardport] Specify the table when adding field to filter
  app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/Option/Collection.php
Labels: 2.3-develop, accept

#14435 Fix bug with retry connect and custom db port
  lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php
Labels: 2.3-develop, accept

#14675 758: update Magento 2 core to support MSI
  app/code/Magento/CatalogSearch/Model/Search/FilterMapper/TermDropdownStrategy/ApplyStockConditionToSelect.php
Labels: 2.3-develop, accept

#14731 MSI-430: Added additional container to shipment form for display extra shipment information (ex. Inventory data)
  app/code/Magento/Shipping/view/adminhtml/layout/adminhtml_order_shipment_new.xml
  app/code/Magento/Shipping/view/adminhtml/layout/adminhtml_order_shipment_view.xml
  app/code/Magento/Shipping/view/adminhtml/templates/create/form.phtml
  app/code/Magento/Shipping/view/adminhtml/templates/view/form.phtml
Labels: 2.3-develop, accept

#12764 magento/magento2#4389 Widget cache error
  app/code/Magento/CatalogWidget/Block/Product/ProductsList.php
  app/code/Magento/CatalogWidget/Test/Unit/Block/Product/ProductsListTest.php
Labels: 2.2-develop, CMS, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, accept, bugfix, mageconf

#14538 [Forwardport] Fix HTML tags in meta description
  app/code/Magento/Catalog/Helper/Product/View.php
Labels: 2.2-develop, accept

#14742 Allow multiple tabs ui_components on a page
  app/code/Magento/Ui/Component/Layout/Tabs.php
Labels: 2.2-develop, accept

#14751 Deleting CMS page via webapi/cron should remove related URL rewrites
  app/code/Magento/CmsUrlRewrite/etc/di.xml
Labels: 2.2-develop, accept

#14770 [Backport] Add expanded documentation to AdapterInterface::update
  lib/internal/Magento/Framework/DB/Adapter/AdapterInterface.php
Labels: 2.1-develop, accept

#14755 Add expanded documentation to AdapterInterface::update
  lib/internal/Magento/Framework/DB/Adapter/AdapterInterface.php
Labels: 2.3-develop, accept

#14771 [Forwardport] Added hyphenation, cutting edge to cutting-edge.
  README.md
Labels: 2.3-develop, accept

#14290 CSS load order incorrect using default_head_blocks.xml #1821
  lib/internal/Magento/Framework/View/Layout/etc/head.xsd
  lib/internal/Magento/Framework/View/Page/Config/Generator/Head.php
  lib/internal/Magento/Framework/View/Page/Config/Reader/Head.php
  lib/internal/Magento/Framework/View/Test/Unit/Page/Config/Generator/HeadTest.php
  lib/internal/Magento/Framework/View/Test/Unit/Page/Config/Reader/HeadTest.php
  lib/internal/Magento/Framework/View/Test/Unit/Page/Config/_files/template_head.xml
Labels: 2.2-develop, accept, distributed-cd

#14707 Catalog price rule save is too slow #13378
  app/code/Magento/CatalogRule/Model/Rule.php
  dev/tests/integration/testsuite/Magento/CatalogRule/Model/RuleTest.php
Labels: 2.2-develop, accept

#14769 [Backport] Add expanded documentation to AdapterInterface::update
  lib/internal/Magento/Framework/DB/Adapter/AdapterInterface.php
Labels: 2.2-develop, accept

#14790 Update Readme file for magento2 repository
  README.md
Labels: 2.2-develop, accept

#14779 [Forwardport] Refactor Code for Mass Order Unhold
  app/code/Magento/Sales/Controller/Adminhtml/Order/MassUnhold.php
  app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/MassUnholdTest.php
Labels: 2.3-develop, accept

#14787 Update Readme file for magento2 repository
  README.md
Labels: 2.3-develop, accept

#14763 [Forwardport] Missing ext-bcmath dependency added
  composer.json
  composer.lock
  lib/internal/Magento/Framework/composer.json
Labels: 2.3-develop, accept

#14772 [Forwardport] Fixed comparison with 0 bug for TableRate shipping carrier
  app/code/Magento/OfflineShipping/Model/ResourceModel/Carrier/Tablerate/RateQuery.php
Labels: 2.3-develop, accept

#14786 [Forwardport] Fixing wrong sitemap product url #4788
  app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php
Labels: 2.3-develop, accept

#14813 [Forwardport] Display Wrong Data On Cart Update Page
  app/code/Magento/Catalog/view/frontend/templates/product/view/form.phtml
  app/code/Magento/Checkout/view/frontend/web/js/view/configure/product-customer-data.js
  app/code/Magento/ConfigurableProduct/view/frontend/web/js/options-updater.js
Labels: 2.3-develop, accept

#14814 [Forwardport] Fix to allow use decimals less then 1 in subproducts qty.
  lib/web/mage/validation/validation.js
Labels: 2.3-develop, accept

#14816 [Forwardport] magento/magento2#4389 Widget cache error
  app/code/Magento/CatalogWidget/Block/Product/ProductsList.php
  app/code/Magento/CatalogWidget/Test/Unit/Block/Product/ProductsListTest.php
Labels: 2.3-develop, accept

#14546 Fix issue #13944. Show Store Views in Terms and Conditions grid.
  app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Grid.php
  app/code/Magento/CheckoutAgreements/Model/ResourceModel/Agreement/Grid/Collection.php
Labels: 2.2-develop, accept

#14726 Fix/navigation order function
  app/code/Magento/Customer/Block/Account/Navigation.php
Labels: 2.2-develop, Partner: Aligent Consulting, accept, partners-contribution

#14845 Updated readme.md file 2.1-develop
  README.md
Labels: 2.1-develop

#14844 Updated readme.md file 2.2-develop
  README.md
Labels: 2.2-develop

#14795 Invoice grid shows wrong shipping & handling for partial items invoice. It shows order's shipping & handling instead if invoiced shipping& handling charge
  app/code/Magento/Sales/etc/di.xml
Labels: 2.2-develop, accept

#14833 Fix a non well formed numeric value encountered on Magento/Directory/…
  app/code/Magento/Directory/Model/Currency.php
Labels: 2.2-develop, accept

#14627 Fix: Datepicker problem when using non en-US locale.
  lib/web/mage/utils/misc.js
Labels: 2.2-develop, accept

#14836 Use index sitemap name as prefix in split sitemaps
  app/code/Magento/Sitemap/Model/Sitemap.php
Labels: 2.2-develop, Partner: Inviqa, Sitemap, accept, partners-contribution

#14839 Back port pull 14301
  app/code/Magento/Search/view/frontend/web/form-mini.js
Labels: 2.2-develop, accept, backport

#12566 Move isAllowed method from AccessChangeQuoteControl to separate service
  app/code/Magento/Quote/Api/ChangeQuoteControlInterface.php
  app/code/Magento/Quote/Model/ChangeQuoteControl.php
  app/code/Magento/Quote/Model/QuoteRepository/Plugin/AccessChangeQuoteControl.php
  app/code/Magento/Quote/Test/Unit/Model/QuoteRepository/Plugin/AccessChangeQuoteControlTest.php
  app/code/Magento/Quote/etc/di.xml
Labels: 2.2-develop, Partner: H&O, accept, partners-contribution

#14699 [2.2] Optimize ID to SKU lookup of tier prices
  app/code/Magento/Catalog/Model/Product/Price/TierPriceStorage.php
Labels: 2.2-develop, Partner: Something Digital, accept, partners-contribution

#14829 Add statement to 'beforeSave' method to allow app:config:import
  app/code/Magento/Braintree/Model/Adminhtml/System/Config/CountryCreditCard.php
Labels: 2.2-develop, accept

#14851 [Forwardport] Invoice grid shows wrong shipping & handling for partial items invoice. It shows order's shipping & handling instead if invoiced shipping& handling charge
  app/code/Magento/Sales/etc/di.xml
Labels: 2.3-develop, accept

#14862 [Forwardport] Fix a non well formed numeric value encountered on Magento/Directory/…
  app/code/Magento/Directory/Model/Currency.php
Labels: 2.3-develop, accept

#14863 [Forwardport] Use index sitemap name as prefix in split sitemaps
  app/code/Magento/Sitemap/Model/Sitemap.php
Labels: 2.3-develop, accept

#14864 [Forwardport] Fix/navigation order function
  app/code/Magento/Customer/Block/Account/Navigation.php
Labels: 2.3-develop, accept

#14866 [Forwardport] Fix: Datepicker problem when using non en-US locale.
  lib/web/mage/utils/misc.js
Labels: 2.3-develop, accept

#14867 [forwardport] PR#12712 : Found 2 elements with non-unique id #email
  app/code/Magento/Customer/view/frontend/web/template/authentication-popup.html
Labels: 2.3-develop, accept

#14868 [Forwardport] Fix issue #13944. Show Store Views in Terms and Conditions grid.
  app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Grid.php
  app/code/Magento/CheckoutAgreements/Model/ResourceModel/Agreement/Grid/Collection.php
Labels: 2.3-develop, accept

#14876 Changed return type of addToCartPostParams to array
  app/code/Magento/Catalog/Block/Product/ListProduct.php
Labels: 2.2-develop, accept

#14892 Corrected @param in comment block
  app/code/Magento/OfflineShipping/Block/Adminhtml/Form/Field/Export.php
Labels: 2.2-develop, accept

#14609 Code cleanup, add more visibility
  app/code/Magento/Rule/Model/Condition/AbstractCondition.php
Labels: 2.2-develop, accept

#14891 Fix typo in doc for updateSpecificCoupons
  app/code/Magento/SalesRule/Model/ResourceModel/Coupon.php
Labels: 2.2-develop, accept

#14893 [Backport] Fix aggregations use statements and return values
  app/code/Magento/Cms/Model/ResourceModel/Block/Grid/Collection.php
  app/code/Magento/Cms/Model/ResourceModel/Page/Grid/Collection.php
  app/code/Magento/Sales/Model/ResourceModel/Grid/Collection.php
Labels: 2.2-develop, Partner: Atwix, accept, backport, partners-contribution

#14901 [Backport] Refactoring: remove unuseful temporary variable
  app/code/Magento/Catalog/Controller/Adminhtml/Category/Save.php
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#14896 Removed extra spaces from language file
  app/code/Magento/CatalogInventory/i18n/en_US.csv
Labels: 2.2-develop, accept

#14906 [Forwardport] Corrected @param in comment block
  app/code/Magento/OfflineShipping/Block/Adminhtml/Form/Field/Export.php
Labels: 2.3-develop, accept, typo

#14907 [Forwardport] Fix typo in doc for updateSpecificCoupons
  app/code/Magento/SalesRule/Model/ResourceModel/Coupon.php
Labels: 2.3-develop, accept, typo

#14905 FIX for issue#14855 - Adding an * to do a customer search
  lib/internal/Magento/Framework/View/Element/UiComponent/DataProvider/FulltextFilter.php
Labels: 2.2-develop, Partner: MageSpecialist, accept, bugfix, partners-contribution

#14899 [Backport] Disable add to cart button when redirect to cart enabled
  app/code/Magento/Catalog/view/frontend/templates/product/view/addtocart.phtml
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#14911 [Backport] Switch updatecart qty input validators to dynamic
  app/code/Magento/Checkout/view/frontend/templates/cart/item/configure/updatecart.phtml
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution

#14902 [Backport] Prices aren't readable when using custom price symbol
  app/design/adminhtml/Magento/backend/Magento_ConfigurableProduct/web/css/source/module/components/_currency-addon.less
Labels: 2.1-develop, Partner: Atwix, accept, backport, partners-contribution
