Repository magento/magento2, pull requests merged in 2021-09, with the labels that each got.

#33919 phpcs fixes for php8
  app/code/Magento/AwsS3/Driver/AwsS3.php
  app/code/Magento/Catalog/Model/Product/ProductFrontendAction/Synchronizer.php
  app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php
  app/code/Magento/Config/App/Config/Source/DumpConfigSourceAggregated.php
  dev/tests/integration/testsuite/Magento/Framework/Jwt/JwtManagerTest.php
  dev/tests/static/testsuite/Magento/Test/Legacy/ObsoleteCodeTest.php
  lib/internal/Magento/Framework/Jwt/JwkFactory.php
  lib/internal/Magento/Framework/Webapi/Rest/Request/Deserializer/Xml.php
  lib/internal/Magento/Framework/Xml/Security.php
Labels: partners-contribution, Partner: Atwix, Award: category of expertise, Progress: ready for testing, Priority: P2, Project: Platform Health

#33967 The `composer.json` files have been stabilised
  app/code/Magento/GraphQl/composer.json
  lib/internal/Magento/Framework/Amqp/composer.json
  lib/internal/Magento/Framework/composer.json
Labels: partners-contribution, Partner: Atwix, Progress: ready for testing, Project: Platform Health

#33515 Update npm packages to recently compatible
  Gruntfile.js.sample
  dev/tests/js/jasmine/spec_runner/index.js
  dev/tests/js/jasmine/spec_runner/tasks/connect.js
  dev/tests/js/jasmine/spec_runner/tasks/jasmine.js
  package.json.sample
Labels: Progress: ready for testing, Auto-Tests: Not Required, Priority: P2, Severity: S3, Project: Platform Health

#33974 Removing the matchMedia polyfill
  app/code/Magento/Theme/view/base/requirejs-config.js
  app/design/adminhtml/Magento/backend/etc/view.xml
  lib/web/matchMedia.js
  lib/web/mediaCheck.js
Labels: partners-contribution, Partner: Atwix, Progress: ready for testing, Auto-Tests: Not Required, Priority: P2, Project: Platform Health

#33992 33916: CE fixed Integration Tests
  dev/tests/integration/testsuite/Magento/CatalogInventory/Model/Quote/Item/QuantityValidatorTest.php
  dev/tests/integration/testsuite/Magento/Paypal/Controller/Billing/AgreementTest.php
Labels: partners-contribution, Partner: Atwix, Progress: ready for testing, Priority: P2, Project: Platform Health

#33983 Updating npm packages
  package.json.sample
Labels: partners-contribution, Partner: Atwix, Progress: ready for testing, Priority: P2, Project: Platform Health

#34021 Revert "Removing the MatchMedia"
  app/code/Magento/Theme/view/base/requirejs-config.js
  app/design/adminhtml/Magento/backend/etc/view.xml
  lib/web/matchMedia.js
  lib/web/mediaCheck.js
Labels: partners-contribution, Partner: Atwix, Progress: ready for testing, Priority: P2, Project: Platform Health

#33363 Updated phpseclib/mcrypt_compat to ^2.0
  composer.json
  composer.lock
  dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testFromClone/composer.lock
  dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testFromCreateProject/composer.lock
  dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testSkeleton/composer.lock
  lib/internal/Magento/Framework/Filesystem/Io/Sftp.php
Labels: Progress: ready for testing, Auto-Tests: Not Required, Priority: P2, Project: Platform Health

#33860 The guzzlehttp/guzzle composer dependency has been updated to version 7.3.0
  composer.json
  composer.lock
  lib/internal/Magento/Framework/View/Design/FileResolution/Fallback/Resolver/Simple.php
  lib/internal/Magento/Framework/composer.json
Labels: partners-contribution, Partner: Atwix, Progress: ready for testing, Priority: P2, Project: Platform Health

#34032 Removing the deprecated npm `grunt-autoprefixer` package
  Gruntfile.js.sample
  dev/tools/grunt/configs/autoprefixer.json
  package.json.sample
Labels: partners-contribution, Partner: Atwix, Progress: ready for testing, Priority: P1, Project: Platform Health

#34062 Added fixes to launch Magento on PHP 8
  app/bootstrap.php
  dev/tests/api-functional/framework/bootstrap.php
  dev/tests/error_handler.php
  dev/tests/integration/framework/bootstrap.php
  dev/tests/integration/testsuite/Magento/Customer/Model/ResourceModel/Grid/CollectionReindexOnAccountLockTest.php
  dev/tests/static/framework/bootstrap.php
  dev/tests/unit/framework/bootstrap.php
  lib/internal/Magento/Framework/Code/Reader/ClassReader.php
  lib/internal/Magento/Framework/Code/Reader/NamespaceResolver.php
  lib/internal/Magento/Framework/DB/AbstractMapper.php
  lib/internal/Magento/Framework/Escaper.php
  lib/internal/Magento/Framework/MessageQueue/Rpc/Publisher.php
  lib/internal/Magento/Framework/Model/AbstractModel.php
  lib/internal/Magento/Framework/Test/Unit/EscaperTest.php
  lib/internal/Magento/Framework/Translate.php
  lib/internal/Magento/Framework/View/Layout/Generator/Block.php
  setup/src/Magento/Setup/Console/CompilerPreparation.php
  setup/src/Magento/Setup/Module/Di/Code/Reader/FileClassScanner.php
  setup/src/Magento/Setup/Module/Di/Code/Reader/FileScanner.php
  setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php
  setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Php/Tokenizer.php
  setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Php/Tokenizer/Token.php
  setup/src/Magento/Setup/Test/Unit/Module/I18n/Parser/Adapter/Php/TokenizerTest.php
Labels: Award: special achievement, partners-contribution, Partner: Atwix, Award: category of expertise, Progress: review, Project: Platform Health

#34104 The magento/zendframework1:dev-master composer dependency has been connected
  composer.json
  composer.lock
  lib/internal/Magento/Framework/Test/Unit/EscaperTest.php
  lib/internal/Magento/Framework/composer.json
Labels: partners-contribution, Partner: Atwix, Component: multiple, Progress: ready for testing, Release Line: 2.4, Priority: P1

#34106 Fixing strict sprintf Phrases in php8
  app/code/Magento/Dhl/Model/Carrier.php
  app/code/Magento/Email/Model/Template/Filter.php
Labels: partners-contribution, Partner: Atwix, Progress: ready for testing, Project: Platform Health

#33682 33589 fix array values in catalogsearch parameters
  app/code/Magento/CatalogSearch/Model/Advanced.php
  app/code/Magento/CatalogSearch/view/frontend/templates/result.phtml
  dev/tests/integration/testsuite/Magento/CatalogSearch/Controller/Advanced/ResultTest.php
Labels: Progress: accept, Area: Frontend, partners-contribution, Partner: Atwix, Component: CatalogSearch, Release Line: 2.4, Auto-Tests: Covered, Priority: P2

#33874 Added "Today" to dashboard report
  app/code/Magento/Backend/Model/Dashboard/Chart/Date.php
  app/code/Magento/Backend/Model/Dashboard/Period.php
  app/code/Magento/Backend/Test/Unit/Model/Dashboard/PeriodTest.php
  app/code/Magento/Reports/Model/ResourceModel/Order/Collection.php
  dev/tests/integration/testsuite/Magento/Backend/Block/Dashboard/Chart/PeriodTest.php
Labels: Progress: accept, Component: Backend, Component: Reports, Release Line: 2.4, Auto-Tests: Covered, Priority: P2

#33903 [Reproducible Builds] Diff in generated/metadata between the builds
  lib/internal/Magento/Framework/Interception/Config/CacheManager.php
  setup/src/Magento/Setup/Module/Di/App/Task/Operation/AppActionListGenerator.php
  setup/src/Magento/Setup/Module/Di/App/Task/Operation/Area.php
  setup/src/Magento/Setup/Module/Di/App/Task/Operation/PluginListGenerator.php
  setup/src/Magento/Setup/Module/Di/Compiler/Config/Reader.php
Labels: Component: Setup, Progress: ready for testing, Component: Interception, Release Line: 2.4, Auto-Tests: Covered, Priority: P2

#33922 Add regions for Belarus
  app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelarus.php
  dev/tests/integration/testsuite/Magento/Directory/Model/RegionTest.php
Labels: Progress: accept, Component: Directory, Release Line: 2.4, Auto-Tests: Covered, Priority: P2

#34000 Extend locales validation - include (3 chars) language codes as valid.
  lib/internal/Magento/Framework/App/Language/package.xsd
Labels: Progress: accept, Component: App, Release Line: 2.4, Auto-Tests: Covered, Priority: P2, Priority: P1

#34001 Fixed customertoken not generating after configured failure in a row
  app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php
Labels: Progress: accept, Component: Integration, Release Line: 2.4, Auto-Tests: Covered, Priority: P1, Severity: S1

#33067 Add aria-label to page jump
  app/code/Magento/Theme/view/frontend/templates/html/pager.phtml
Labels: Progress: accept, Area: Frontend, Component: Theme, Release Line: 2.4, Auto-Tests: Not Required, Priority: P2, Risk: low

#33124 [ReadMe] updated readMe file for QuoteBundleOptions-ReleaseNotification modules
  app/code/Magento/QuoteBundleOptions/README.md
  app/code/Magento/QuoteConfigurableOptions/README.md
  app/code/Magento/QuoteDownloadableLinks/README.md
  app/code/Magento/QuoteGraphQl/README.md
  app/code/Magento/RelatedProductGraphQl/README.md
  app/code/Magento/ReleaseNotification/README.md
Labels: Progress: accept, partners-contribution, Partner: Atwix, Component: ReleaseNotification, Release Line: 2.4, Component: QuoteGraphQl, Auto-Tests: Not Required, Priority: P2, Component: QuoteBundleOptions, Component: QuoteConfigurableOptions, Component: QuoteDownloadableLinks, Component: RelatedProductGraphQl

#33449 Inheriting from a class that doesn't exist#33334
  app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php
  app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php
Labels: Progress: accept, Award: bug fix, Component: Bundle, Release Line: 2.4, Auto-Tests: Covered, Priority: P1

#34175 Fixed restrictions for `colinmollenhour/cache-backend-redis` composer dependency
  app/code/Magento/Catalog/Model/ResourceModel/Category.php
  app/code/Magento/Catalog/Model/ResourceModel/Category/Flat.php
Labels: partners-contribution, Partner: Atwix, Progress: ready for testing, Priority: P2, Project: Platform Health

#34176 34020: Removed bind category_id
  app/code/Magento/Catalog/Model/ResourceModel/Category.php
  app/code/Magento/Catalog/Model/ResourceModel/Category/Flat.php
Labels: partners-contribution, Partner: Atwix, Progress: pending review, Priority: P1

#34153 php8 compatibility/fix integration test Magento_Swatches module
  dev/tests/integration/testsuite/Magento/Swatches/Controller/Adminhtml/Product/AttributeTest.php
Labels: Progress: needs update, partners-contribution, Partner: Atwix, Priority: P1, Project: Platform Health

#34045 Fix Unit tests to be compatible with php8 [part 1]
  app/code/Magento/Captcha/Test/Unit/Model/DefaultTest.php
  app/code/Magento/Catalog/Model/ProductLink/CollectionProvider.php
  app/code/Magento/CatalogImportExport/Test/Unit/Model/Import/ProductTest.php
  app/code/Magento/CatalogInventory/Test/Unit/Model/Config/Backend/ManagestockTest.php
  app/code/Magento/CatalogRule/Test/Unit/Model/RuleTest.php
  app/code/Magento/CatalogUrlRewrite/Observer/AfterImportDataObserver.php
  app/code/Magento/Customer/Test/Unit/Model/Metadata/Form/FileTest.php
  app/code/Magento/ImportExport/Test/Unit/Model/Import/EntityAbstractTest.php
  app/code/Magento/Quote/Test/Unit/Model/Quote/Item/UpdaterTest.php
  app/code/Magento/Quote/Test/Unit/Model/QuoteManagementTest.php
  app/code/Magento/SalesRule/Test/Unit/Model/Quote/DiscountTest.php
  app/code/Magento/SalesRule/Test/Unit/Model/RulesApplierTest.php
  app/code/Magento/Theme/Controller/Adminhtml/System/Design/Theme/Delete.php
  app/code/Magento/Theme/Controller/Adminhtml/System/Design/Theme/DownloadCustomCss.php
  app/code/Magento/Theme/Test/Unit/Controller/Adminhtml/System/Design/Theme/DownloadCustomCssTest.php
  dev/tests/static/framework/Magento/TestFramework/Integrity/Library/Injectable.php
  lib/internal/Magento/Framework/Code/Test/Unit/Generator/EntityAbstractTest.php
  lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php
  lib/internal/Magento/Framework/DB/Test/Unit/DB/Statement/MysqlTest.php
  lib/internal/Magento/Framework/DataObject/Test/Unit/CopyTest.php
  lib/internal/Magento/Framework/Locale/Test/Unit/TranslatedListsTest.php
  lib/internal/Magento/Framework/Session/Test/Unit/SaveHandlerTest.php
  lib/internal/Magento/Framework/Validator/Test/Unit/CurrencyTest.php
  lib/internal/Magento/Framework/Validator/Test/Unit/LocaleTest.php
  lib/internal/Magento/Framework/Validator/Test/Unit/TimezoneTest.php
  lib/internal/Magento/Framework/View/Template/Html/Minifier.php
  lib/internal/Magento/Framework/View/Test/Unit/Layout/Generator/BlockTest.php
  lib/internal/Magento/Framework/Xml/Security.php
  setup/src/Magento/Setup/Test/Unit/Module/Di/Code/Generator/InterceptionConfigurationBuilderTest.php
Labels: Award: special achievement, partners-contribution, Partner: Atwix, Award: category of expertise, Progress: review, Priority: P1, Project: Platform Health
