Repository magento/magento2, pull requests merged in 2021-10, with the labels that each got.

#34047 CE Fix Unit tests to be compatible with php8 [part 2]
  app/code/Magento/Email/Model/Template.php
  app/code/Magento/Theme/Model/Indexer/Design/Config.php
  lib/internal/Magento/Framework/Filesystem/Driver/Http.php
  lib/internal/Magento/Framework/Filter/Template.php
  lib/internal/Magento/Framework/Indexer/Test/Unit/MultiDimensionProviderTest.php
Labels: partners-contribution, Partner: Atwix, Progress: review, Priority: P1, Project: Platform Health

#34198 Fixes wepApi functional tests php8 compatibility
  app/code/Magento/Directory/Model/PriceCurrency.php
  app/code/Magento/SalesGraphQl/Model/OrderItem/DataProvider.php
  app/code/Magento/SalesGraphQl/Model/Resolver/CreditMemo/CreditMemoItems.php
  app/code/Magento/SalesGraphQl/Model/Resolver/CreditMemo/CreditMemoTotal.php
  app/code/Magento/SalesGraphQl/Model/Resolver/Invoice/InvoiceItems.php
  app/code/Magento/SalesGraphQl/Model/Resolver/Invoice/InvoiceTotal.php
  app/code/Magento/SalesGraphQl/Model/Resolver/OrderTotal.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductPriceTest.php
Labels: partners-contribution, Partner: Atwix, Progress: review, Project: Platform Health

#34192 Fix static tests to be php8 compatible
  dev/tests/api-functional/framework/Magento/TestFramework/Authentication/Rest/CurlClient.php
  dev/tests/static/framework/Magento/TestFramework/Integrity/Library/PhpParser/StaticCalls.php
  dev/tests/static/framework/Magento/TestFramework/Integrity/Library/PhpParser/Throws.php
  dev/tests/static/testsuite/Magento/Test/Integrity/Di/CompilerTest.php
  dev/tests/static/testsuite/Magento/Test/Integrity/Magento/Framework/Api/ExtensibleInterfacesTest.php
  dev/tests/static/testsuite/Magento/Test/Integrity/PublicCodeTest.php
  dev/tests/static/testsuite/Magento/Test/Integrity/Readme/ReadmeTest.php
Labels: partners-contribution, Partner: Atwix, Progress: ready for testing, Project: Platform Health

#34191 fix Newsletter Queue method for a case with invalid start_at param
  app/code/Magento/Newsletter/Model/Queue.php
  dev/tests/integration/testsuite/Magento/Newsletter/Controller/Adminhtml/NewsletterQueueTest.php
  dev/tests/integration/testsuite/Magento/Newsletter/_files/queue.php
Labels: Progress: needs update, partners-contribution, Partner: Atwix, Award: category of expertise, Priority: P1, Project: Platform Health
