Repository magento/magento2, pull requests merged in 2022-08, with the labels that each got.

#35436 Add "Last Updated At" Column to Admin Product Grid
  app/code/Magento/Catalog/view/adminhtml/ui_component/product_listing.xml
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#35441 Fix Passing null to parameter #1 ($string) of type string
  lib/internal/Magento/Framework/Amqp/Config.php
Labels: Progress: accept, Priority: P1

#35524 Improve price index consistency and run time
  app/code/Magento/Catalog/Model/Indexer/Product/Price/AbstractAction.php
Labels: Progress: accept, Priority: P1

#35540 Add missing semicolons for 'const' and 'let'
  lib/web/jquery/bootstrap/collapse.js
  lib/web/jquery/bootstrap/dom/data.js
  lib/web/jquery/bootstrap/dom/event-handler.js
  lib/web/jquery/bootstrap/dom/manipulator.js
  lib/web/jquery/bootstrap/dom/selector-engine.js
  lib/web/jquery/bootstrap/tab.js
  lib/web/jquery/bootstrap/util/index.js
Labels: Progress: accept, partners-contribution, Award: bug fix, Partner: Fisheye, Auto-Tests: Not Required, Priority: P2, Severity: S2

#30590 [Fixed] - SalesRule module collection missing event prefix
  app/code/Magento/SalesRule/Model/ResourceModel/Rule/Collection.php
Labels: Progress: accept, Component: SalesRule, Release Line: 2.4, Auto-Tests: Not Required, Triage: Dev.Experience, Priority: P2, Severity: S2

#32889 32824-generated-associated-product-name
  app/code/Magento/ConfigurableProduct/view/adminhtml/web/js/components/dynamic-rows-configurable.js
Labels: Progress: accept, Area: Frontend, partners-contribution, Partner: Atwix, Component: ConfigurableProduct, Release Line: 2.4, Auto-Tests: Not Covered, Priority: P2

#35656 Add class for styling modal shipping-address
  app/code/Magento/Checkout/view/frontend/layout/checkout_index_index.xml
Labels: improvement, Progress: pending review, Priority: P3, Risk: low

#35797 Issue #34545 PHP Version error do not send a proper code error
  app/bootstrap.php
Labels: Progress: ready for testing, Auto-Tests: Not Required, Priority: P4, Risk: low

#35817 Fix missing scope on isShippingCarrierAvailable
  app/code/Magento/Shipping/Model/Shipping.php
Labels: Progress: pending review, Priority: P3

#35818 Update table creation information in README.md
  app/code/Magento/Authorization/README.md
Labels: Progress: pending review, Priority: P2

#35848 Set shared=false for SortOrderBuilder
  app/etc/di.xml
Labels: Progress: accept, Auto-Tests: Not Required, Priority: P2, Severity: S3, Risk: low

#35853 Accept any throwable exceptions in newrelic wrapper
  app/code/Magento/NewRelicReporting/Model/NewRelicWrapper.php
Labels: Progress: accept, Priority: P2

#35321 Fix php error in profiler when using PHP 8.1
  lib/internal/Magento/Framework/Profiler/Driver/Standard/Stat.php
  lib/internal/Magento/Framework/Profiler/Test/Unit/Driver/Standard/StatTest.php
Labels: Progress: accept, Priority: P1

#35572 Support the use of PHP 8.0 "mixed" type
  lib/internal/Magento/Framework/Async/Code/Generator/ProxyDeferredGenerator.php
  lib/internal/Magento/Framework/Code/Generator/EntityAbstract.php
  lib/internal/Magento/Framework/Interception/Code/Generator/Interceptor.php
  lib/internal/Magento/Framework/ObjectManager/Code/Generator/Proxy.php
  lib/internal/Magento/Framework/ObjectManager/Test/Unit/Code/Generator/ProxyTest.php
  lib/internal/Magento/Framework/ObjectManager/Test/Unit/Code/Generator/_files/SampleMixed.php
  lib/internal/Magento/Framework/ObjectManager/Test/Unit/Code/Generator/_files/SampleMixedProxy.txt
Labels: Progress: accept, Award: test coverage, Award: bug fix, Auto-Tests: Covered, Priority: P2, Severity: S1

#34061 Fixed the welcome message contains single quote character
  app/code/Magento/Theme/Block/Html/Header.php
  app/code/Magento/Theme/Test/Unit/Block/Html/HeaderTest.php
  app/code/Magento/Theme/view/frontend/templates/html/header.phtml
  app/code/Magento/Translation/Model/Inline/Parser.php
Labels: Progress: accept, Area: Frontend, Component: Theme, Release Line: 2.4, Priority: P1, Reported on 2.4.x
