Repository magento/magento2, pull requests merged in 2022-11, with the labels that each got.

#36458 Update code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: Progress: accept

#36241 Fix order spam when search engine is down
  app/code/Magento/CatalogInventory/Observer/ReindexQuoteInventoryObserver.php
  app/code/Magento/CatalogInventory/Test/Unit/Observer/ReindexQuoteInventoryObserverTest.php
Labels: Progress: accept, Priority: P2, QA: Added to Regression Scope

#36335 Issue 36309: Undefined value sets in the variant's sku
  app/code/Magento/ConfigurableProduct/view/adminhtml/web/js/variations/variations.js
Labels: Progress: accept, Priority: P1, QA: Added to Regression Scope

#36352 Issue 36351: fix bin/magento setup:upgrade error when use composer install --no-dev
  lib/internal/Magento/Framework/Api/SearchCriteria/CollectionProcessor/FilterProcessor.php
Labels: Progress: accept, Priority: P1

#36371 PR magento/magento2#35535: Magento 2.4.4 Mini cart item images not showing
  lib/internal/Magento/Framework/Image/Adapter/Gd2.php
  lib/internal/Magento/Framework/Image/Adapter/ImageMagick.php
Labels: Progress: accept, Priority: P2, QA: Added to Regression Scope

#36379 get.php - check existence of required config array items
  pub/get.php
Labels: Progress: accept, Priority: P2

#36411 Allow items to be shipped with a qty > 0 and < 1 #35972 #36232
  app/code/Magento/Sales/Test/Unit/Model/Order/ShipmentFactoryTest.php
Labels: Progress: accept, Priority: P2

#35846 Remove redundant getCacheTags method from the Topmenu class
  app/code/Magento/Theme/Block/Html/Topmenu.php
Labels: Progress: accept, Priority: P3

#35033 Clean up `catalogrule_product_price_replica` table
  app/code/Magento/CatalogRule/Setup/Patch/Schema/CleanUpProductPriceReplicaTable.php
Labels: Progress: accept, Component: CatalogRule, partners-contribution, Award: bug fix, Release Line: 2.4, Partner: Fisheye, Auto-Tests: Not Required, Priority: P2

#33803 ISSUE-33802: ensure that deployment config will reload its data, if t…
  lib/internal/Magento/Framework/App/DeploymentConfig.php
  lib/internal/Magento/Framework/App/Test/Unit/DeploymentConfigTest.php
Labels: Progress: accept, Award: bug fix, Award: category of expertise, Component: App, Release Line: 2.4, Auto-Tests: Covered, Priority: P1, Severity: S1

#32481 Added token revocation for REST API
  app/code/Magento/Integration/etc/webapi.xml
  dev/tests/api-functional/testsuite/Magento/Customer/Api/AccountManagementRevokeCustomerTokenTest.php
Labels: Progress: accept, Award: test coverage, partners-contribution, Partner: Atwix, Component: Integration, Release Line: 2.4, Auto-Tests: Covered, Priority: P2, Priority: P1, Severity: S1, QA: Added to Regression Scope

#31606 Ensure that invoice comments are returned when requested by GraphQL queries
  app/code/Magento/Sales/Test/Fixture/InvoiceComment.php
  app/code/Magento/SalesGraphQl/Model/Resolver/Invoices.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Sales/InvoiceTest.php
Labels: Progress: accept, partners-contribution, Partner: Aligent Consulting, Award: bug fix, Release Line: 2.4, Auto-Tests: Covered, Component: SalesGraphQl, Priority: P2, Severity: S3, Project: GraphQL

#30413 29217: Fixed - Prefix and Suffix Translation
  app/code/Magento/Customer/Block/Address/Renderer/DefaultRenderer.php
  app/code/Magento/Customer/Helper/View.php
  app/code/Magento/Customer/Model/Address/AbstractAddress.php
  app/code/Magento/Customer/Model/Options.php
  app/code/Magento/Customer/view/frontend/templates/widget/name.phtml
  app/code/Magento/Sales/Model/Order/Address.php
Labels: Component: Customer, Component: Sales, Area: Frontend, Progress: ready for testing, Release Line: 2.4, Auto-Tests: Not Required, Priority: P3, Severity: S3, QA: Added to Regression Scope, Event: dmcdindia2020
