Repository magento/magento2, pull requests merged in 2022-12, with the labels that each got.

#36348 #36346 Add regions for Czech Republic
  app/code/Magento/Directory/Setup/Patch/Data/AddDataForCzechia.php
Labels: Progress: accept, Priority: P2

#36495 Remove laminas/laminas-dependency-plugin dependency
  composer.json
  composer.lock
Labels: Progress: accept, Priority: P2

#36027 magento/magento2#12075: Customer Email with diacritics isn't allowed
  app/code/Magento/Eav/Model/Attribute/Data/Text.php
  app/code/Magento/Eav/Test/Unit/Model/Attribute/Data/TextTest.php
Labels: Progress: accept, partners-contribution, Priority: P1, Severity: S1, Partner: Perspective Studio

#36187 Remove 'version' manipulation from sampledata:deploy, improve success messaging
  app/code/Magento/SampleData/Console/Command/SampleDataDeployCommand.php
  app/code/Magento/SampleData/Test/Unit/Console/Command/AbstractSampleDataCommandTest.php
  app/code/Magento/SampleData/Test/Unit/Console/Command/SampleDataDeployCommandTest.php
  app/code/Magento/SampleData/Test/Unit/Console/Command/SampleDataRemoveCommandTest.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#35807 Removed a fixed version phpcs dependency from the project
  composer.json
Labels: Progress: accept, partners-contribution, Priority: P2, Partner: MRM Commerce

#34252 Fix issue when ProductRepository::save method was loosing 2nd argument value
  app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php
  app/code/Magento/ConfigurableProduct/Test/Unit/Model/Plugin/ProductRepositorySaveTest.php
Labels: Progress: accept, Award: bug fix, Component: ConfigurableProduct, Release Line: 2.4, Auto-Tests: Not Required, Priority: P2, Severity: S1

#36355 Fix bulk action log clean error on admin dashboard
  app/code/Magento/AsynchronousOperations/Controller/Adminhtml/Notification/Dismiss.php
Labels: Progress: pending review, Priority: P2, Severity: S3

#35564 MariaDB Casting is too slow
  app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Eav/Source.php
Labels: Progress: accept, partners-contribution, Partner: Interactiv4, Award: bug fix, Auto-Tests: Not Required, Priority: P2, Severity: S2, Area: Performance

#36098 Issue 36049: Catalog Price Rule single product reindex works incorrectly
  app/code/Magento/CatalogRule/Model/Indexer/IndexBuilder.php
  app/code/Magento/CatalogRule/Model/Indexer/ReindexRuleProduct.php
  app/code/Magento/CatalogRule/Model/Rule.php
  app/code/Magento/CatalogRule/Test/Unit/Model/Indexer/ReindexRuleProductTest.php
Labels: Progress: pending review, Priority: P1

#36173 Issue 35284: Hitting enter when configuring a product to add to order…
  app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/composite/configure.phtml
  app/code/Magento/Sales/Test/Mftf/ActionGroup/AddConfigurableProductToOrderPressKeyEnterActionGroup.xml
  app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderWithConfigurableProductPressKeyEnterTest.xml
Labels: Award: bug fix, Progress: testing in progress, Auto-Tests: Covered, Priority: P3

#36239 Improve error messaging when merged XML is invalid
  lib/internal/Magento/Framework/Config/Reader/Filesystem.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Auto-Tests: Not Required, Priority: P2, Project: Community Picked

#35216 Fix typo which trigger performance bug
  app/code/Magento/Catalog/Model/ResourceModel/Category/Collection.php
Labels: Progress: accept, Component: Catalog, Release Line: 2.4, Auto-Tests: Not Required, Priority: P1, Project: Community Picked

#33841 Add regions for Ukraine
  app/code/Magento/Directory/Setup/Patch/Data/AddDataForUkraine.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/CreateCustomerAddressTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetBillingAddressOnCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetShippingAddressOnCartTest.php
  dev/tests/integration/testsuite/Magento/Directory/Model/RegionTest.php
Labels: Progress: accept, Component: Directory, Release Line: 2.4, Priority: P2, Project: Community Picked

#34117 Add --exclude-group to cron:run
  app/code/Magento/Cron/Console/Command/CronCommand.php
  app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php
  dev/tests/integration/testsuite/Magento/Cron/Observer/ProcessCronQueueObserverTest.php
Labels: Progress: accept, Component: Cron, partners-contribution, Partner: Ampersand, Release Line: 2.4, Auto-Tests: Covered, Priority: P3, Project: Community Picked

#30647 Initialize authentication popup modal only when needed
  app/code/Magento/Captcha/Test/Mftf/Section/StorefrontCustomerSignInFormSection.xml
  app/code/Magento/Checkout/Test/Mftf/ActionGroup/AssertStorefrontGuestCheckoutShippingAddressFormPrefilledActionGroup.xml
  app/code/Magento/Checkout/Test/Mftf/ActionGroup/GuestCheckoutFillNewBillingAddressActionGroup.xml
  app/code/Magento/Checkout/Test/Mftf/ActionGroup/GuestCheckoutFillNewShippingAddressActionGroup.xml
  app/code/Magento/Checkout/Test/Mftf/ActionGroup/GuestCheckoutFillingShippingSectionActionGroup.xml
  app/code/Magento/Checkout/Test/Mftf/ActionGroup/GuestCheckoutFillingShippingSectionUnavailablePaymentActionGroup.xml
  app/code/Magento/Checkout/Test/Mftf/ActionGroup/GuestCheckoutFillingShippingSectionWithoutRegionActionGroup.xml
  app/code/Magento/Checkout/Test/Mftf/ActionGroup/LoginAsCustomerOnCheckoutPageActionGroup.xml
  app/code/Magento/Checkout/Test/Mftf/ActionGroup/StorefrontShippmentFromActionGroup.xml
  app/code/Magento/Checkout/Test/Mftf/Section/CheckoutShippingGuestInfoSection.xml
  app/code/Magento/Checkout/Test/Mftf/Section/CheckoutShippingSection.xml
  app/code/Magento/Checkout/Test/Mftf/Section/CheckoutSuccessMainSection.xml
  app/code/Magento/Checkout/Test/Mftf/Section/CheckoutSuccessRegisterSection.xml
  app/code/Magento/Checkout/Test/Mftf/Test/StorefrontOnePageCheckoutDataWhenChangeQtyTest.xml
  app/code/Magento/Checkout/Test/Mftf/Test/StorefrontProductNameMinicartOnCheckoutPageDifferentStoreViewsTest.xml
  app/code/Magento/CheckoutAgreements/Test/Mftf/ActionGroup/StorefrontProcessCheckoutToPaymentActionGroup.xml
  app/code/Magento/Customer/Test/Mftf/Page/StorefrontCustomerSignInPage.xml
  app/code/Magento/Customer/Test/Mftf/Section/StorefrontCustomerLoginSignUpSection.xml
  app/code/Magento/Customer/Test/Mftf/Section/StorefrontCustomerSignInFormSection/StorefrontCustomerSignInFormSection.xml
  app/code/Magento/Customer/Test/Mftf/Test/StorefrontLoginFormShowPasswordTest.xml
  app/code/Magento/Customer/view/frontend/web/js/view/authentication-popup.js
  app/code/Magento/Multishipping/Test/Mftf/Test/StoreFrontCheckVatIdAtAccountCreateWithMultishipmentTest.xml
  app/code/Magento/Newsletter/Test/Mftf/Section/StorefrontNewsletterManageSection.xml
  app/code/Magento/Tax/Test/Mftf/Test/StorefrontTaxQuoteCheckoutTest/StorefrontTaxQuoteCheckoutGuestSimpleTest.xml
  dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/view/authentication-popup.test.js
Labels: Progress: accept, Component: Tax, Component: Customer, Component: Checkout, Area: Frontend, Component: Captcha, partners-contribution, Component: Multishipping, Component: Newsletter, Component: CheckoutAgreements, Award: category of expertise, Release Line: 2.4, Partner: creativestyle, Auto-Tests: Covered, Priority: P2, Severity: S3, Area: Perf/Frontend, QA: Added to Regression Scope, Project: Community Picked
