Repository magento/magento2, pull requests merged in 2023-05, with the labels that each got.

#37296 magento/magento2#36928: 504 gateway timeout when creating configurabl…
  app/code/Magento/Catalog/etc/adminhtml/di.xml
Labels: Progress: accept, partners-contribution, Priority: P0, QA: Added to Regression Scope, Partner: Perspective Studio

#35658 Skip is_scalar for null values when imploding multiline address
  app/code/Magento/Customer/Model/Address/AbstractAddress.php
  app/code/Magento/Customer/Test/Unit/Model/Address/AbstractAddressTest.php
Labels: Progress: accept, Priority: P2, QA: Added to Regression Scope

#35053 #32910 fix rewriting category product URL for the one store group
  app/code/Magento/CatalogUrlRewrite/Model/ProductScopeRewriteGenerator.php
  app/code/Magento/CatalogUrlRewrite/Test/Unit/Model/ProductScopeRewriteGeneratorTest.php
  dev/tests/integration/testsuite/Magento/Catalog/Model/Product/UrlTest.php
  dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/UrlRewriteHandlerTest.php
  dev/tests/integration/testsuite/Magento/Quote/Model/ShippingMethodManagementTest.php
Labels: Progress: accept, Component: CatalogUrlRewrite, partners-contribution, Partner: Atwix, Release Line: 2.4, Priority: P2

#33092 Prune triggers after setting database up properly
  setup/src/Magento/Setup/Console/Command/UpgradeCommand.php
Labels: Progress: accept, Component: Setup, partners-contribution, Release Line: 2.4, Partner: Fisheye, Priority: P1

#36578 Fixed issue The js error when click on video thumbnail in product gallery fullscreen mode
  app/code/Magento/ProductVideo/view/frontend/web/js/fotorama-add-video-events.js
Labels: Progress: accept, Area: Frontend, partners-contribution, Award: bug fix, Component: ProductVideo, Priority: P1, QA: Added to Regression Scope, Partner: Perspective Studio

#36099 fix(eav): fetch option value from its option_id as stated by OptionValueProvider
  app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/OptionValueProvider.php
Labels: Progress: review, Priority: P2

#37341 Fixes regression bug introduced in AC-8077 where the html 'id' and 'f…
  app/code/Magento/Bundle/view/frontend/templates/catalog/product/view/type/bundle/option/radio.phtml
Labels: Progress: review, Priority: P1

#37355 Fix broken fotorama image slider on mobile Fixes #37232
  lib/web/fotorama/fotorama.js
Labels: Progress: needs update, Priority: P1

#37354 Revert of #36041 PR. Remove magento/module-grouped-product dependency
  app/code/Magento/Catalog/Ui/DataProvider/Product/Listing/Collector/Price.php
  app/code/Magento/Catalog/composer.json
  app/code/Magento/Catalog/view/frontend/templates/product/view/opengraph/general.phtml
  app/code/Magento/Cms/Test/Mftf/Test/AdminAddWidgetToWYSIWYGWithTaxRuleForBundleProductInRecentlyViewedWidgetTest.xml
  app/code/Magento/GroupedProduct/view/base/web/template/product/price/special_price.html
  app/code/Magento/GroupedProduct/view/frontend/ui_component/widget_recently_viewed.xml
Labels: Progress: accept, Priority: P2

#36769 Fix `Call to a member function getId() on int`
  app/code/Magento/Customer/Block/Adminhtml/Edit/Tab/Newsletter.php
  app/code/Magento/Customer/Test/Unit/Block/Adminhtml/Edit/Tab/NewsletterTest.php
Labels: Progress: accept, partners-contribution, Partner: Ampersand, Component: Newsletter, Auto-Tests: Covered, Triage: Dev.Experience, Priority: P3, Area: Admin UI, Project: Community Picked

#36028 magento/magento2#35906 GraphQL Routes query with fragments has issue in the category page #35906
  app/code/Magento/CatalogGraphQl/Model/Category/DepthCalculator.php
  app/code/Magento/CatalogGraphQl/Test/Unit/Model/Resolver/Category/DepthCalculatorTest.php
Labels: Progress: accept, partners-contribution, Priority: P2, QA: Added to Regression Scope, Partner: Perspective Studio, Project: Community Picked

#36323 Can't able to delete/rename sitemap.xml in file system
  app/code/Magento/Sitemap/Controller/Adminhtml/Sitemap/Delete.php
  app/code/Magento/Sitemap/Controller/Adminhtml/Sitemap/Save.php
  app/code/Magento/Sitemap/Test/Unit/Controller/Adminhtml/Sitemap/DeleteTest.php
Labels: Progress: accept, Priority: P2, Project: Community Picked
