Repository magento/magento2, pull requests merged in 2023-08, with the labels that each got.

#36496 Fix - 36409:- Update disable_auto_group_change in Customer Import
  app/code/Magento/CustomerImportExport/Model/Import/Customer.php
Labels: Progress: pending review, Priority: P2

#36216 Issue 36208: Multiple Store views - Admin - Category page - Sorting by Product Name issue
  app/code/Magento/Catalog/Block/Adminhtml/Category/Tab/Product.php
Labels: Progress: pending review, Priority: P2

#37730 Fixed: Incorrect discount amount for whole cart
  app/code/Magento/SalesRule/Model/Validator.php
Labels: Progress: accept, Priority: P2, Project: Community Picked

#37871 Log Aggregation fix on Checkout failure (group by reason, not Quote ID)
  app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php
  app/code/Magento/Checkout/Model/PaymentInformationManagement.php
Labels: Progress: accept, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#37298 magento/magento2#37028: [Sales] Missing relation data when reorder
  app/code/Magento/Sales/Model/AdminOrder/Create.php
  dev/tests/integration/testsuite/Magento/Sales/Model/AdminOrder/CreateTest.php
Labels: Progress: accept, partners-contribution, Priority: P2, Partner: Perspective Studio, Project: Community Picked

#37479 Avoid divide-by-zero fatal error
  app/code/Magento/Cron/Model/Schedule.php
  app/code/Magento/Cron/Test/Unit/Model/ScheduleTest.php
Labels: Progress: accept, partners-contribution, Partner: Youwe, Auto-Tests: Covered, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#37563 Tailwindui css layout support - Add more htmlClasses
  lib/internal/Magento/Framework/View/Layout/etc/elements.xsd
Labels: Progress: accept, Auto-Tests: Not Required, Priority: P2

#37578 Added: SKU with configurable, group, bundle product Title
  app/code/Magento/Paypal/Model/Cart.php
Labels: Progress: accept, Priority: P3, Project: Community Picked

#37188 Footer > update old link with Github issues
  app/code/Magento/Theme/view/frontend/templates/html/bugreport.phtml
  app/code/Magento/Theme/view/frontend/templates/html/footer.phtml
Labels: Progress: accept, partners-contribution, Partner: Le Site, Priority: P2

#37302 Fix missing jQuery widget dependency
  lib/web/mage/trim-input.js
Labels: Progress: accept, Priority: P2

#37560 Fixed: $row() undefined issue while inline edit after delete item from database
  app/code/Magento/Ui/view/base/web/js/grid/columns/column.js
  app/code/Magento/Ui/view/base/web/js/grid/editing/editor-view.js
  app/code/Magento/Ui/view/base/web/templates/grid/cells/actions.html
  app/code/Magento/Ui/view/base/web/templates/grid/cells/multiselect.html
  app/code/Magento/Ui/view/base/web/templates/grid/listing.html
Labels: Progress: accept, Auto-Tests: Not Required, Priority: P2, Project: Community Picked

#37688 Update Ga.php to fix no revenue data in GA4
  app/code/Magento/GoogleGtag/Block/Ga.php
  app/code/Magento/GoogleGtag/Test/Unit/Block/GaTest.php
Labels: Progress: accept, Priority: P3, Project: Community Picked

#36836 feat: more informative error message on xml validation errors
  app/code/Magento/Backend/Test/Unit/Model/Menu/Config/_files/invalidMenuXmlArray.php
  app/code/Magento/Catalog/Test/Unit/Model/Attribute/Config/XsdTest.php
  app/code/Magento/Catalog/Test/Unit/Model/ProductOptions/Config/_files/invalidProductOptionsMergedXmlArray.php
  app/code/Magento/Catalog/Test/Unit/Model/ProductOptions/Config/_files/invalidProductOptionsXmlArray.php
  app/code/Magento/Catalog/Test/Unit/Model/ProductTypes/Config/_files/invalidProductTypesMergedXmlArray.php
  app/code/Magento/Catalog/Test/Unit/Model/ProductTypes/Config/_files/invalidProductTypesXmlArray.php
  app/code/Magento/Config/Test/Unit/Model/Config/_files/invalidSystemXmlArray.php
  app/code/Magento/Cron/Test/Unit/Model/Config/XsdTest.php
  app/code/Magento/Customer/Test/Unit/Model/Address/Config/XsdTest.php
  app/code/Magento/Eav/Test/Unit/Model/Entity/Attribute/Config/_files/invalidEavAttributeXmlArray.php
  app/code/Magento/Email/Test/Unit/Model/Template/Config/XsdTest.php
  app/code/Magento/ImportExport/Test/Unit/Model/Export/Config/_files/invalidExportMergedXmlArray.php
  app/code/Magento/ImportExport/Test/Unit/Model/Export/Config/_files/invalidExportXmlArray.php
  app/code/Magento/ImportExport/Test/Unit/Model/Import/Config/_files/invalidImportMergedXmlArray.php
  app/code/Magento/ImportExport/Test/Unit/Model/Import/Config/_files/invalidImportXmlArray.php
  app/code/Magento/Integration/Test/Unit/Model/Config/Consolidated/XsdTest.php
  app/code/Magento/Integration/Test/Unit/Model/Config/Integration/XsdTest.php
  app/code/Magento/Integration/Test/Unit/Model/Config/XsdTest.php
  app/code/Magento/Sales/Test/Unit/Model/Config/XsdTest.php
  app/code/Magento/Sales/Test/Unit/Model/Order/Pdf/Config/XsdTest.php
  dev/tests/static/testsuite/Magento/Test/Integrity/Magento/Framework/Cache/_files/invalidCacheConfigXmlArray.php
  lib/internal/Magento/Framework/Acl/Test/Unit/AclResource/Config/_files/invalidAclXmlArray.php
  lib/internal/Magento/Framework/Acl/Test/Unit/AclResource/Config/_files/invalidMergedAclXmlArray.php
  lib/internal/Magento/Framework/Api/Test/Unit/ExtensionAttribute/Config/XsdTest.php
  lib/internal/Magento/Framework/App/Test/Unit/Config/Initial/_files/invalidConfigXmlArray.php
  lib/internal/Magento/Framework/App/Test/Unit/Config/_files/invalidRoutesXmlArray.php
  lib/internal/Magento/Framework/App/Test/Unit/ResourceConnection/Config/_files/invalidResourcesXmlArray.php
  lib/internal/Magento/Framework/Config/Dom.php
  lib/internal/Magento/Framework/Config/Test/Unit/DomTest.php
  lib/internal/Magento/Framework/Data/Test/Unit/Argument/_files/typesInvalidArray.php
  lib/internal/Magento/Framework/Event/Test/Unit/Config/_files/invalidEventsXmlArray.php
  lib/internal/Magento/Framework/Indexer/Test/Unit/_files/invalidIndexerXmlArray.php
  lib/internal/Magento/Framework/MessageQueue/Test/Unit/Consumer/Config/XsdTest.php
  lib/internal/Magento/Framework/MessageQueue/Test/Unit/Publisher/XsdTest.php
  lib/internal/Magento/Framework/MessageQueue/Test/Unit/Topology/MergedXsdTest.php
  lib/internal/Magento/Framework/MessageQueue/Test/Unit/Topology/XsdTest.php
  lib/internal/Magento/Framework/Mview/Test/Unit/_files/invalidMviewXmlArray.php
  lib/internal/Magento/Framework/ObjectManager/Test/Unit/Config/_files/invalidConfigXmlArray.php
  lib/internal/Magento/Framework/TestFramework/Test/Unit/Unit/Utility/XsdValidatorTest.php
  lib/internal/Magento/Framework/View/Test/Unit/Layout/_files/invalidLayoutArgumentsXmlArray.php
Labels: Progress: accept, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#36030 Fix for issue 27474
  app/code/Magento/Sales/Block/Adminhtml/Order/AbstractOrder.php
  app/code/Magento/Sales/Block/Adminhtml/Order/View/Info.php
  app/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/View.php
  app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/View.php
  app/code/Magento/Sales/Test/Mftf/Section/AdminInvoiceOrderInformationSection.xml
  app/code/Magento/Sales/Test/Mftf/Test/AdminInvoiceOrderInvoiceEmailSentTest.xml
  app/code/Magento/Sales/i18n/en_US.csv
  app/code/Magento/Sales/view/adminhtml/templates/order/creditmemo/view/form.phtml
  app/code/Magento/Sales/view/adminhtml/templates/order/invoice/view/form.phtml
  app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/View.php
  app/code/Magento/Shipping/Test/Unit/Controller/Adminhtml/Order/Shipment/ViewTest.php
  app/code/Magento/Shipping/i18n/en_US.csv
  app/code/Magento/Shipping/view/adminhtml/templates/view/form.phtml
  app/design/adminhtml/Magento/backend/Magento_Sales/web/css/source/module/_order.less
  app/design/adminhtml/Magento/backend/Magento_Sales/web/css/source/module/order/_info.less
Labels: Progress: accept, partners-contribution, Priority: P2, QA: Added to Regression Scope, Partner: Perspective Studio, Project: Community Picked

#36155 Fixed duplicated ids to index by mview changelog
  app/code/Magento/Eav/Model/Mview/ChangelogBatchWalker/IdsFetcher.php
  app/code/Magento/Eav/Model/Mview/ChangelogBatchWalker/IdsSelectBuilder.php
  app/code/Magento/Eav/Model/Mview/ChangelogBatchWalker/IdsTableBuilder.php
  app/code/Magento/Eav/etc/di.xml
  lib/internal/Magento/Framework/Mview/Config/Converter.php
  lib/internal/Magento/Framework/Mview/Test/Unit/ViewSubscribeTest.php
  lib/internal/Magento/Framework/Mview/Test/Unit/ViewTest.php
  lib/internal/Magento/Framework/Mview/Test/Unit/_files/mview_config.php
  lib/internal/Magento/Framework/Mview/View.php
  lib/internal/Magento/Framework/Mview/View/ChangeLogBatchWalker.php
  lib/internal/Magento/Framework/Mview/View/ChangeLogBatchWalkerInterface.php
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalker.php
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalker/IdsContext.php
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalker/IdsFetcher.php
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalker/IdsFetcherInterface.php
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalker/IdsSelectBuilder.php
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalker/IdsSelectBuilderInterface.php
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalker/IdsTableBuilder.php
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalker/IdsTableBuilderInterface.php
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalkerFactory.php
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalkerInterface.php
  lib/internal/Magento/Framework/Mview/etc/mview.xsd
Labels: Progress: accept, Award: bug fix, Award: category of expertise, Triage: Dev.Experience, Priority: P1, Severity: S0, Project: Community Picked

#36345 Improve performance of DataObject magic calls and addData()
  app/code/Magento/Paypal/Model/Payflow/Request.php
  lib/internal/Magento/Framework/DataObject.php
  lib/internal/Magento/Framework/Test/Unit/DataObjectTest.php
Labels: Progress: accept, partners-contribution, Award: category of expertise, Partner: Youwe, Triage: Dev.Experience, Priority: P2, Area: Performance, Project: Community Picked

#33918 [PHPMD] Add phpmd rule with ignoring of unused required parameters in the plugins
  app/code/Magento/Catalog/Plugin/CategoryAuthorization.php
  app/code/Magento/Catalog/Plugin/ProductAuthorization.php
  app/code/Magento/Catalog/Plugin/RemoveImagesFromGalleryAfterRemovingProduct.php
  dev/tests/static/framework/Magento/CodeMessDetector/Rule/UnusedCode/UnusedFormalParameter.php
  dev/tests/static/framework/Magento/CodeMessDetector/Test/Unit/Rule/UnusedCode/UnusedFormalParameterTest.php
  dev/tests/static/framework/Magento/CodeMessDetector/resources/rulesets/unusedcode.xml
  dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml
Labels: Progress: accept, Component: Catalog, Award: test coverage, Award: bug fix, Award: category of expertise, Release Line: 2.4, Auto-Tests: Covered, Triage: Dev.Experience, Priority: P3, Severity: S4, Risk: low, Project: Community Picked

#34557 Show customer_grid indexer as green when realtime
  app/code/Magento/Indexer/Block/Backend/Grid/Column/Renderer/Scheduled.php
  app/code/Magento/Indexer/Test/Unit/Block/Backend/Grid/Column/Renderer/ScheduledTest.php
  app/code/Magento/Indexer/composer.json
  app/code/Magento/Indexer/etc/module.xml
Labels: Progress: accept, partners-contribution, Component: Indexer, Release Line: 2.4, Partner: Fisheye, Priority: P3, Project: Community Picked

#36022 Replaced `CREATE TEMPORARY TABLE ... LIKE`with different approach
  lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php
Labels: Progress: accept, Triage: Dev.Experience, Priority: P1, Project: Community Picked

#32904 Import/Export - Fix 'entity values are mixed' exception when no valid data
  app/code/Magento/ImportExport/Model/Import.php
  app/code/Magento/ImportExport/Test/Unit/Model/ImportTest.php
  dev/tests/integration/testsuite/Magento/ImportExport/Model/ImportTest.php
Labels: Progress: accept, Component: ImportExport, Award: test coverage, partners-contribution, Award: bug fix, Release Line: 2.4, Partner: Fisheye, Auto-Tests: Covered, Priority: P3, QA: Added to Regression Scope, Project: Community Picked

#32158 Removed unused plugin on protected method
  app/code/Magento/Dhl/Model/Plugin/Checkout/Block/Cart/Shipping.php
  app/code/Magento/Dhl/etc/di.xml
  app/code/Magento/OfflineShipping/Model/Plugin/Checkout/Block/Cart/Shipping.php
  app/code/Magento/OfflineShipping/Test/Unit/Model/Plugin/Checkout/Block/Cart/ShippingTest.php
  app/code/Magento/OfflineShipping/etc/di.xml
Labels: Progress: accept, Component: OfflineShipping, Component: Dhl, Release Line: 2.4, Auto-Tests: Covered, Triage: Dev.Experience, Priority: P3, Project: Community Picked
