Repository magento/magento2, pull requests merged in 2023-07, with the labels that each got.

#37282 Fix image order when 10+ images on dropdown configurable products
  app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js
Labels: Progress: accept, Priority: P2, QA: Added to Regression Scope

#37387 Correctly handle order clause for reserved columns
  lib/internal/Magento/Framework/Data/Collection/AbstractDb.php
  lib/internal/Magento/Framework/Data/Test/Unit/Collection/DbTest.php
Labels: Progress: accept, partners-contribution, Award: bug fix, Partner: Youwe, Auto-Tests: Covered, Priority: P2

#36590 magento/magento2#36431: Undefined index in TierPriceValidator.php
  app/code/Magento/Catalog/Model/Product/Price/Validation/TierPriceValidator.php
  app/code/Magento/Customer/Controller/Adminhtml/Group/Save.php
  dev/tests/api-functional/testsuite/Magento/Catalog/Api/TierPriceStorageTest.php
Labels: Progress: accept, partners-contribution, Priority: P3, Partner: Perspective Studio, Project: Community Picked

#35762 Allow forwarding to noroute admin route
  lib/internal/Magento/Framework/App/Action/Forward.php
Labels: Progress: accept, partners-contribution, Award: bug fix, Partner: Fisheye, Auto-Tests: Not Required, Priority: P2, Severity: S2

#35773 Add note to setCustomer on quote about quote addresses removal
  app/code/Magento/Quote/Model/Quote.php
Labels: Progress: accept, Priority: P1, Severity: S1

#36039 magento/magento2#35706 Remote storage issue #35706
  app/code/Magento/Sales/Model/Order/Pdf/AbstractPdf.php
  lib/internal/Magento/Framework/File/Pdf/Image.php
  lib/internal/Magento/Framework/File/Pdf/ImageResource/ImageFactory.php
  lib/internal/Magento/Framework/Test/Unit/File/Pdf/ImageResource/ImageFactoryTest.php
Labels: Progress: accept, partners-contribution, Priority: P2, Partner: Perspective Studio, Project: Community Picked

#33189 New file AddDataForCostaRica.php
  app/code/Magento/Directory/Setup/Patch/Data/AddDataForCostaRica.php
Labels: Progress: accept, Component: Directory, Release Line: 2.4, Priority: P2

#36966 GraphQL: Incl. Tax for Product Price on Order Item
  app/code/Magento/SalesGraphQl/Model/OrderItem/DataProvider.php
Labels: Progress: needs update, Priority: P1
