Repository magento/magento2, pull requests merged in 2023-09, with the labels that each got.

#37745 Usps add new allowed methods
  app/code/Magento/Usps/Helper/Data.php
  app/code/Magento/Usps/Model/Carrier.php
  app/code/Magento/Usps/Setup/Patch/Data/UpdateAllowedMethods.php
  app/code/Magento/Usps/Test/Unit/Helper/DataTest.php
  app/code/Magento/Usps/Test/Unit/Model/CarrierTest.php
  app/code/Magento/Usps/etc/config.xml
  app/code/Magento/Usps/i18n/en_US.csv
Labels: Progress: review, Priority: P1

#37573 Fixed PHP 8.2 deprecation warnings: 'creation of dynamic property'.
  app/code/Magento/CatalogImportExport/Model/Export/Product.php
  app/code/Magento/Dhl/Model/Carrier.php
  app/code/Magento/Fedex/Model/Carrier.php
  app/code/Magento/ImportExport/Model/Export/Entity/AbstractEntity.php
  app/code/Magento/Shipping/Model/Carrier/AbstractCarrier.php
  app/code/Magento/Ups/Model/Carrier.php
  app/code/Magento/Usps/Model/Carrier.php
  dev/tests/integration/testsuite/Magento/Setup/Fixtures/FixturesAsserts/SimpleProductsAssert.php
  pub/errors/processor.php
Labels: Progress: ready for testing, Triage: Dev.Experience, Priority: P2

#33421 #33220 memorize toolbar parameters for catalogsearch
  app/code/Magento/CatalogSearch/Observer/ToolbarMemorizerObserver.php
  app/code/Magento/CatalogSearch/etc/frontend/events.xml
Labels: Progress: extended testing, Priority: P2
