Repository magento/magento2, pull requests merged in 2023-03, with the labels that each got.

#35392 [FEATURE][issue#32554] Added caching to the storeConfig GraphQl Endpoint
  app/code/Magento/StoreGraphQl/Model/Resolver/Store/Identity.php
  app/code/Magento/StoreGraphQl/etc/schema.graphqls
Labels: partners-contribution, Partner: Experius, Release Line: 2.4, Component: StoreGraphQl, Progress: pending review, Priority: P1, Project: GraphQL

#36864 NEW PR for #36422: Only Update Indexer Mode When Required
  app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassChangelog.php
  app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassOnTheFly.php
  app/code/Magento/Indexer/Test/Mftf/ActionGroup/AdminSwitchAllIndexerToActionModeActionGroup.xml
  app/code/Magento/Indexer/Test/Mftf/ActionGroup/AdminSwitchIndexerToActionModeActionGroup.xml
  app/code/Magento/Indexer/Test/Mftf/Section/AdminIndexManagementSection.xml
  app/code/Magento/Indexer/Test/Unit/Controller/Adminhtml/Indexer/MassOnTheFlyTest.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P3, Project: Community Picked

#36798 Expiration period is now hours instead of days
  app/code/Magento/Customer/Model/Customer.php
Labels: Progress: accept, Component: Customer, partners-contribution, Auto-Tests: Not Covered, Triage: Dev.Experience, Priority: P2, Partner: Dn’D

#36583 Issue #36582 - Unable to create new customer address on specific website
  app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Source/CountryWithWebsites.php
Labels: Progress: accept, Auto-Tests: Not Covered, Priority: P1

#36668 Correct mime type typo
  app/code/Magento/Catalog/Controller/Adminhtml/Product/Gallery/Upload.php
Labels: Progress: accept, Priority: P2

#36715 Fixes deprecated jquery call to focus in validation library.
  lib/web/mage/validation.js
Labels: Progress: accept, Priority: P2

#36177 Re-apply fix for JS error in the customer data
  app/code/Magento/Customer/view/frontend/web/js/customer-data.js
Labels: Progress: accept, Area: Frontend, Priority: P2

#36257 Update validation.js to properly indicate required fields for accessibility
  lib/web/mage/validation.js
Labels: Progress: accept, Priority: P2

#36321 Improve performance of getData retrieval
  lib/internal/Magento/Framework/DataObject.php
Labels: Progress: accept, Award: category of expertise, Triage: Dev.Experience, Priority: P2, Area: Performance

#35101 reference directive restored for _extends.less. extends replaced to mixins in _extend.less
  app/design/frontend/Magento/blank/web/css/source/_extends.less
  app/design/frontend/Magento/blank/web/css/source/_sources.less
Labels: Progress: accept, Area: Design/Frontend, Release Line: 2.4, Auto-Tests: Not Required, Triage: Dev.Experience, Priority: P2

#34323 Fix Varnish VCL Template to use path without /pub to health_check.php
  app/code/Magento/PageCache/etc/varnish4.vcl
  app/code/Magento/PageCache/etc/varnish5.vcl
  app/code/Magento/PageCache/etc/varnish6.vcl
Labels: Progress: accept, Component: PageCache, Release Line: 2.4, Auto-Tests: Not Required, Triage: Dev.Experience, Priority: P2, Severity: S3

#36754 Replace {YYYY} in the copyright line by the current year
  app/code/Magento/Theme/Block/Html/Footer.php
  app/code/Magento/Theme/Test/Unit/Block/Html/FooterTest.php
  app/code/Magento/Theme/i18n/en_US.csv
  app/code/Magento/Theme/view/adminhtml/ui_component/design_config_form.xml
Labels: Progress: accept, Priority: P2, Project: Community Picked

#36436 Fix - Newrelic GraphQl transaction names not working
  app/code/Magento/GraphQl/Model/Query/Logger/NewRelic.php
Labels: Progress: accept, partners-contribution, Partner: Ampersand, Priority: P2, QA: Added to Regression Scope, Project: Community Picked

#36041 magento/magento2#35881: Final Price for grouped products does not include tax in the Recently Viewed Widget
  app/code/Magento/Catalog/Test/Mftf/Section/StoreFrontRecentProductSection.xml
  app/code/Magento/Catalog/Ui/DataProvider/Product/Listing/Collector/Price.php
  app/code/Magento/Catalog/composer.json
  app/code/Magento/Catalog/view/frontend/templates/product/view/opengraph/general.phtml
  app/code/Magento/Cms/Test/Mftf/Test/AdminAddWidgetToWYSIWYGWithTaxRuleForBundleProductInRecentlyViewedWidgetTest.xml
  app/code/Magento/GroupedProduct/view/base/web/template/product/price/special_price.html
  app/code/Magento/GroupedProduct/view/frontend/ui_component/widget_recently_viewed.xml
Labels: Progress: accept, partners-contribution, Priority: P2, QA: Added to Regression Scope, Reported on 2.4.0, Partner: Perspective Studio, Project: Community Picked

#29173 Fix potentially corrupt merged CSS files.
  lib/internal/Magento/Framework/View/Asset/MergeStrategy/Direct.php
  lib/internal/Magento/Framework/View/Test/Unit/Asset/MergeStrategy/DirectTest.php
Labels: Progress: accept, Area: Frontend, Award: bug fix, Component: View, Release Line: 2.4, Auto-Tests: Covered, Triage: Dev.Experience, Priority: P3, Severity: S3, Project: Community Picked

#34092 Enforce array type in DesignTheme config processor
  app/code/Magento/Theme/Model/Config/Processor/DesignTheme.php
Labels: Progress: accept, partners-contribution, Component: Theme, Partner: integer_net GmbH, Release Line: 2.4, Auto-Tests: Not Required, Triage: Dev.Experience, Priority: P2, Priority: P4, Project: Community Picked
