Repository magento/magento2, pull requests merged in 2023-10, with the labels that each got.

#36977 Remove forbidden `@author` tag from `Magento_Review`
  app/code/Magento/Review/Block/Adminhtml/Add.php
  app/code/Magento/Review/Block/Adminhtml/Add/Form.php
  app/code/Magento/Review/Block/Adminhtml/Grid/Filter/Type.php
  app/code/Magento/Review/Block/Adminhtml/Grid/Renderer/Type.php
  app/code/Magento/Review/Block/Adminhtml/Product/Grid.php
  app/code/Magento/Review/Block/Adminhtml/Rating.php
  app/code/Magento/Review/Block/Adminhtml/Rating/Edit/Form.php
  app/code/Magento/Review/Block/Adminhtml/Rating/Edit/Tabs.php
  app/code/Magento/Review/Block/Customer/View.php
  app/code/Magento/Review/Block/Form.php
  app/code/Magento/Review/Block/Form/Configure.php
  app/code/Magento/Review/Block/Product/Review.php
  app/code/Magento/Review/Block/Product/View.php
  app/code/Magento/Review/Block/Rating/Entity/Detailed.php
  app/code/Magento/Review/Block/View.php
  app/code/Magento/Review/Model/Rating.php
  app/code/Magento/Review/Model/Rating/Entity.php
  app/code/Magento/Review/Model/Rating/Option.php
  app/code/Magento/Review/Model/Rating/Option/Vote.php
  app/code/Magento/Review/Model/ResourceModel/Rating.php
  app/code/Magento/Review/Model/ResourceModel/Rating/Collection.php
  app/code/Magento/Review/Model/ResourceModel/Rating/Entity.php
  app/code/Magento/Review/Model/ResourceModel/Rating/Grid/Collection.php
  app/code/Magento/Review/Model/ResourceModel/Rating/Option/Collection.php
  app/code/Magento/Review/Model/ResourceModel/Rating/Option/Vote.php
  app/code/Magento/Review/Model/ResourceModel/Rating/Option/Vote/Collection.php
  app/code/Magento/Review/Model/ResourceModel/Review/Status.php
  app/code/Magento/Review/Model/ResourceModel/Review/Status/Collection.php
  app/code/Magento/Review/Model/ResourceModel/Review/Summary.php
  app/code/Magento/Review/Model/ResourceModel/Review/Summary/Collection.php
  app/code/Magento/Review/Model/Review/Status.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#37017 Remove forbidden `@author` tag from Tax module
  app/code/Magento/Tax/Block/Adminhtml/Rate/Form.php
  app/code/Magento/Tax/Block/Adminhtml/Rate/Grid/Renderer/Data.php
  app/code/Magento/Tax/Block/Adminhtml/Rate/Title.php
  app/code/Magento/Tax/Block/Adminhtml/Rate/Title/Fieldset.php
  app/code/Magento/Tax/Block/Adminhtml/Rate/Toolbar/Add.php
  app/code/Magento/Tax/Block/Adminhtml/Rate/Toolbar/Save.php
  app/code/Magento/Tax/Block/Adminhtml/Rule.php
  app/code/Magento/Tax/Block/Item/Price/Renderer.php
  app/code/Magento/Tax/Controller/Adminhtml/Rate.php
  app/code/Magento/Tax/Controller/Adminhtml/Rule.php
  app/code/Magento/Tax/Controller/Adminhtml/Tax.php
  app/code/Magento/Tax/Model/Calculation/Rate/Title.php
  app/code/Magento/Tax/Model/Calculation/RateFactory.php
  app/code/Magento/Tax/Model/Config.php
  app/code/Magento/Tax/Model/ResourceModel/Calculation/Collection.php
  app/code/Magento/Tax/Model/ResourceModel/Calculation/Rate.php
  app/code/Magento/Tax/Model/ResourceModel/Calculation/Rate/Title.php
  app/code/Magento/Tax/Model/ResourceModel/Calculation/Rate/Title/Collection.php
  app/code/Magento/Tax/Model/ResourceModel/Calculation/Rule.php
  app/code/Magento/Tax/Model/ResourceModel/Calculation/Rule/Collection.php
  app/code/Magento/Tax/Model/ResourceModel/Report/Collection.php
  app/code/Magento/Tax/Model/ResourceModel/Report/Tax/Createdat.php
  app/code/Magento/Tax/Model/ResourceModel/Report/Tax/Updatedat.php
  app/code/Magento/Tax/Model/ResourceModel/Report/Updatedat/Collection.php
  app/code/Magento/Tax/Model/ResourceModel/Sales/Order/Tax.php
  app/code/Magento/Tax/Model/ResourceModel/Sales/Order/Tax/Collection.php
  app/code/Magento/Tax/Model/ResourceModel/TaxClass.php
  app/code/Magento/Tax/Model/ResourceModel/TaxClass/Collection.php
  app/code/Magento/Tax/Model/System/Config/Source/Tax/Display/Type.php
  app/code/Magento/Widget/Block/Adminhtml/Widget/Chooser.php
  app/code/Magento/Widget/Block/Adminhtml/Widget/Form.php
  app/code/Magento/Widget/Block/Adminhtml/Widget/Instance.php
  app/code/Magento/Widget/Block/Adminhtml/Widget/Instance/Edit.php
  app/code/Magento/Widget/Block/Adminhtml/Widget/Instance/Edit/Chooser/Template.php
  app/code/Magento/Widget/Block/Adminhtml/Widget/Instance/Edit/Form.php
  app/code/Magento/Widget/Block/Adminhtml/Widget/Instance/Edit/Tab/Main.php
  app/code/Magento/Widget/Block/Adminhtml/Widget/Instance/Edit/Tab/Properties.php
  app/code/Magento/Widget/Block/Adminhtml/Widget/Instance/Edit/Tab/Settings.php
  app/code/Magento/Widget/Block/Adminhtml/Widget/Instance/Edit/Tabs.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#37019 Remove forbidden `@author` tag from framework (part 2)
  lib/internal/Magento/Framework/Data/Form/Element/AbstractElement.php
  lib/internal/Magento/Framework/Data/Form/Element/Button.php
  lib/internal/Magento/Framework/Data/Form/Element/Checkbox.php
  lib/internal/Magento/Framework/Data/Form/Element/Checkboxes.php
  lib/internal/Magento/Framework/Data/Form/Element/Collection.php
  lib/internal/Magento/Framework/Data/Form/Element/Column.php
  lib/internal/Magento/Framework/Data/Form/Element/Date.php
  lib/internal/Magento/Framework/Data/Form/Element/Editablemultiselect.php
  lib/internal/Magento/Framework/Data/Form/Element/Editor.php
  lib/internal/Magento/Framework/Data/Form/Element/Fieldset.php
  lib/internal/Magento/Framework/Data/Form/Element/File.php
  lib/internal/Magento/Framework/Data/Form/Element/Gallery.php
  lib/internal/Magento/Framework/Data/Form/Element/Hidden.php
  lib/internal/Magento/Framework/Data/Form/Element/Imagefile.php
  lib/internal/Magento/Framework/Data/Form/Element/Link.php
  lib/internal/Magento/Framework/Data/Form/Element/Multiline.php
  lib/internal/Magento/Framework/Data/Form/Element/Multiselect.php
  lib/internal/Magento/Framework/Data/Form/Element/Note.php
  lib/internal/Magento/Framework/Data/Form/Element/Obscure.php
  lib/internal/Magento/Framework/Data/Form/Element/Password.php
  lib/internal/Magento/Framework/Data/Form/Element/Radio.php
  lib/internal/Magento/Framework/Data/Form/Element/Radios.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#36978 Remove forbidden `@author` tag from `Magento_Wishlist`
  app/code/Magento/Wishlist/Block/Customer/Sharing.php
  app/code/Magento/Wishlist/Block/Customer/Wishlist.php
  app/code/Magento/Wishlist/Block/Customer/Wishlist/Button.php
  app/code/Magento/Wishlist/Block/Customer/Wishlist/Item/Column/Actions.php
  app/code/Magento/Wishlist/Block/Customer/Wishlist/Item/Column/Comment.php
  app/code/Magento/Wishlist/Block/Customer/Wishlist/Item/Column/Edit.php
  app/code/Magento/Wishlist/Block/Customer/Wishlist/Item/Column/Info.php
  app/code/Magento/Wishlist/Block/Customer/Wishlist/Item/Column/Remove.php
  app/code/Magento/Wishlist/Block/Share/Wishlist.php
  app/code/Magento/Wishlist/Helper/Data.php
  app/code/Magento/Wishlist/Model/ResourceModel/Item.php
  app/code/Magento/Wishlist/Model/ResourceModel/Item/Option.php
  app/code/Magento/Wishlist/Model/ResourceModel/Item/Option/Collection.php
  app/code/Magento/Wishlist/Model/ResourceModel/Wishlist.php
  app/code/Magento/Wishlist/Model/ResourceModel/Wishlist/Collection.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#36981 Remove forbidden `@author` tag
  app/code/Magento/UrlRewrite/Block/Catalog/Category/Tree.php
  app/code/Magento/UrlRewrite/Block/Catalog/Product/Grid.php
  app/code/Magento/UrlRewrite/Block/Cms/Page/Grid.php
  app/code/Magento/User/Block/Role.php
  app/code/Magento/User/Block/User.php
  app/code/Magento/User/Block/User/Edit.php
  app/code/Magento/User/Block/User/Edit/Tabs.php
  app/code/Magento/User/Model/ResourceModel/Role/User/Collection.php
  app/code/Magento/User/Model/ResourceModel/User/Locked/Collection.php
  app/code/Magento/Variable/Model/ResourceModel/Variable.php
  app/code/Magento/Variable/Model/ResourceModel/Variable/Collection.php
  app/code/Magento/Weee/Block/Item/Price/Renderer.php
  app/code/Magento/Weee/Model/ResourceModel/Attribute/Backend/Weee/Tax.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#36987 Remove forbidden `@author` tag from `Magento_Catalog` (part 1)
  app/code/Magento/Catalog/Block/Adminhtml/Category/Checkboxes/Tree.php
  app/code/Magento/Catalog/Block/Adminhtml/Category/Helper/Image.php
  app/code/Magento/Catalog/Block/Adminhtml/Category/Helper/Pricestep.php
  app/code/Magento/Catalog/Block/Adminhtml/Category/Helper/Sortby/Available.php
  app/code/Magento/Catalog/Block/Adminhtml/Category/Helper/Sortby/DefaultSortby.php
  app/code/Magento/Catalog/Block/Adminhtml/Category/Tab/Product.php
  app/code/Magento/Catalog/Block/Adminhtml/Category/Widget/Chooser.php
  app/code/Magento/Catalog/Block/Adminhtml/Form.php
  app/code/Magento/Catalog/Block/Adminhtml/Form/Renderer/Config/DateFieldsOrder.php
  app/code/Magento/Catalog/Block/Adminhtml/Form/Renderer/Config/YearRange.php
  app/code/Magento/Catalog/Block/Adminhtml/Form/Renderer/Fieldset/Element.php
  app/code/Magento/Catalog/Block/Adminhtml/Helper/Form/Wysiwyg.php
  app/code/Magento/Catalog/Block/Adminhtml/Helper/Form/Wysiwyg/Content.php
  app/code/Magento/Catalog/Block/Adminhtml/Product.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Edit/Form.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Edit/Tab/Front.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Edit/Tab/Main.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Edit/Tab/Options.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Edit/Tab/System.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Edit/Tabs.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Grid.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/NewAttribute/Product/Attributes.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Set/Main.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Set/Main/Formattribute.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Set/Main/Formgroup.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Set/Main/Tree/Attribute.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Set/Main/Tree/Group.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Set/Toolbar/Add.php
  app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Set/Toolbar/Main.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#36999 Remove forbidden `@author` tag from `Magento_Customer` (part 1)
  app/code/Magento/Customer/Block/Address/Book.php
  app/code/Magento/Customer/Block/Address/Renderer/RendererInterface.php
  app/code/Magento/Customer/Block/Adminhtml/Form/Element/Boolean.php
  app/code/Magento/Customer/Block/Adminhtml/Form/Element/File.php
  app/code/Magento/Customer/Block/Adminhtml/Form/Element/Image.php
  app/code/Magento/Customer/Block/Adminhtml/Grid/Filter/Country.php
  app/code/Magento/Customer/Block/Adminhtml/Grid/Renderer/Multiaction.php
  app/code/Magento/Customer/Block/Adminhtml/Group.php
  app/code/Magento/Customer/Block/Adminhtml/Sales/Order/Address/Form/Renderer/Vat.php
  app/code/Magento/Customer/Block/Adminhtml/System/Config/Validatevat.php
  app/code/Magento/Customer/Block/Form/Login.php
  app/code/Magento/Customer/Controller/Adminhtml/System/Config/Validatevat.php
  app/code/Magento/Customer/Model/Address/Form.php
  app/code/Magento/Customer/Model/Attribute/Backend/Data/Boolean.php
  app/code/Magento/Customer/Model/Attribute/Data/AbstractData.php
  app/code/Magento/Customer/Model/Attribute/Data/Boolean.php
  app/code/Magento/Customer/Model/Attribute/Data/Date.php
  app/code/Magento/Customer/Model/Attribute/Data/File.php
  app/code/Magento/Customer/Model/Attribute/Data/Hidden.php
  app/code/Magento/Customer/Model/Attribute/Data/Image.php
  app/code/Magento/Customer/Model/ResourceModel/Group/Collection.php
  app/code/Magento/Customer/Model/ResourceModel/Online/Grid/Collection.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#37013 Remove forbidden `@author` tag
  app/code/Magento/Sales/Block/Items/AbstractItems.php
  app/code/Magento/Sales/Block/Order/Creditmemo.php
  app/code/Magento/Sales/Block/Order/Email/Creditmemo/Items.php
  app/code/Magento/Sales/Block/Order/Email/Items.php
  app/code/Magento/Sales/Block/Order/Email/Items/DefaultItems.php
  app/code/Magento/Sales/Block/Order/Email/Items/Order/DefaultOrder.php
  app/code/Magento/Sales/Block/Order/Info.php
  app/code/Magento/Sales/Block/Order/Invoice/Items.php
  app/code/Magento/Sales/Block/Order/Items.php
  app/code/Magento/Sales/Controller/Adminhtml/Order/Create.php
  app/code/Magento/Sales/Controller/Adminhtml/Order/View/Giftmessage.php
  app/code/Magento/Sales/Controller/Adminhtml/Transactions.php
  app/code/Magento/Sales/Helper/Data.php
  app/code/Magento/Sales/Model/AdminOrder/Product/Quote/Initializer.php
  app/code/Magento/Sales/Model/Config/Ordered.php
  app/code/Magento/Sales/Model/Order/Creditmemo/Total/AbstractTotal.php
  app/code/Magento/Sales/Model/Order/Invoice/Total/AbstractTotal.php
  app/code/Magento/Sales/Model/Order/Invoice/Total/Shipping.php
  app/code/Magento/Sales/Model/Order/Payment/Transaction.php
  app/code/Magento/Sales/Model/Order/Shipment/Track.php
  app/code/Magento/Sales/Model/Order/Tax.php
  app/code/Magento/Sales/Model/Order/Total/AbstractTotal.php
  app/code/Magento/Sales/Model/ResourceModel/HelperInterface.php
  app/code/Magento/Sales/Model/ResourceModel/Order.php
  app/code/Magento/Sales/Model/ResourceModel/Order/Attribute/Backend/Billing.php
  app/code/Magento/Sales/Model/ResourceModel/Order/Attribute/Backend/Child.php
  app/code/Magento/Sales/Model/ResourceModel/Order/Attribute/Backend/Shipping.php
  app/code/Magento/Sales/Model/ResourceModel/Order/Collection.php
  app/code/Magento/Sales/Model/ResourceModel/Order/Collection/AbstractCollection.php
  app/code/Magento/Sales/Model/ResourceModel/Order/Comment/Collection/AbstractCollection.php
  app/code/Magento/Sales/Model/ResourceModel/Order/Creditmemo.php
  app/code/Magento/Sales/Model/ResourceModel/Order/Creditmemo/Attribute/Backend/Child.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#34608 Comma too much in calender
  app/code/Magento/Theme/view/frontend/templates/js/calendar.phtml
Labels: Progress: accept, Area: Frontend, Component: Theme, Cleanup, Release Line: 2.4, Auto-Tests: Not Required, Priority: P3, Severity: S4, Risk: low

#31058 Fix error message in StockItemValidator.php
  app/code/Magento/CatalogInventory/Model/StockItemValidator.php
Labels: Progress: accept, Component: CatalogInventory, Release Line: 2.4, Auto-Tests: Not Required, Priority: P3, Severity: S3, QA: Added to Regression Scope

#37876 Fixed : Meta title issue on product page for Page title suffix
  app/code/Magento/Catalog/Helper/Product/View.php
  dev/tests/integration/testsuite/Magento/Catalog/Helper/Product/ViewTest.php
Labels: Progress: accept, Priority: P3, Project: Community Picked

#37785 Fixed typo in unit test introduced by accident in e0c61dee13afcd10c03…
  app/code/Magento/Catalog/Test/Unit/Model/Category/Attribute/Backend/SortbyTest.php
Labels: Progress: accept, Auto-Tests: Covered, Priority: P2, Risk: low

#37861 fixed HTML characters issue at getAlt() function
  app/code/Magento/Catalog/Ui/Component/Listing/Columns/Thumbnail.php
Labels: Progress: pending review, Priority: P3

#37862 37607 rest configurable products SKU childrenendpoint missing media gallery entries
  app/code/Magento/Catalog/Ui/Component/Listing/Columns/Thumbnail.php
  app/code/Magento/ConfigurableProduct/Model/LinkManagement.php
  app/code/Magento/ConfigurableProduct/Test/Unit/Model/LinkManagementTest.php
Labels: Progress: accept, Priority: P2, Project: Community Picked

#37868 magento/magento2#37864: Removed unused class from ProductRepository
  app/code/Magento/Catalog/Model/ProductRepository.php
  app/code/Magento/Catalog/Test/Unit/Model/ProductRepositoryTest.php
Labels: Progress: accept, partners-contribution, Triage: Dev.Experience, Priority: P1, Partner: Perspective Studio, Project: Community Picked

#37434 Fix issue when Proxy class wasn't generated during di compile
  setup/src/Magento/Setup/Module/Di/Code/Scanner/XmlScanner.php
  setup/src/Magento/Setup/Test/Unit/Module/Di/Code/Reader/ClassesScannerTest.php
  setup/src/Magento/Setup/Test/Unit/Module/Di/Code/Scanner/XmlScannerTest.php
  setup/src/Magento/Setup/Test/Unit/Module/Di/_files/app/code/Magento/SomeModule/NestedElement.php
  setup/src/Magento/Setup/Test/Unit/Module/Di/_files/app/code/Magento/SomeModule/etc/di.xml
Labels: Progress: accept, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#37477 Improve product edit page loading speed
  app/code/Magento/Ui/view/base/web/js/lib/view/utils/dom-observer.js
Labels: Progress: accept, help wanted, Priority: P3, Severity: S3, Area: Performance, Project: Community Picked

#37629 Cleanup of some non-existing classes from some unit tests code in the…
  lib/internal/Magento/Framework/Filesystem/Test/Unit/File/ExcludeFilterTest.php
  lib/internal/Magento/Framework/ObjectManager/Test/Unit/Factory/CompiledTest.php
  lib/internal/Magento/Framework/ObjectManager/Test/Unit/Helper/SortItemsTest.php
  lib/internal/Magento/Framework/Pricing/Test/Unit/Render/PriceBoxTest.php
  lib/internal/Magento/Framework/TestFramework/Unit/Helper/ObjectManager.php
  lib/internal/Magento/Framework/Webapi/Test/Unit/Rest/Request/DeserializerFactoryTest.php
Labels: Progress: accept, Priority: P2

#36696 Changes of GR(Greece) PostCode Pattern
  app/code/Magento/Directory/etc/zip_codes.xml
  dev/tests/integration/testsuite/Magento/Directory/Model/Country/Postcode/ValidatorTest.php
Labels: Progress: accept, Priority: P3, Project: Community Picked

#36008 magento/magento2#35952 Admin Users unable to change front-end Logo in Design Config when in Single Store Mode
  app/code/Magento/Sales/Test/Unit/ViewModel/Header/LogoPathResolverTest.php
  app/code/Magento/Sales/ViewModel/Header/LogoPathResolver.php
  app/code/Magento/Theme/Test/Unit/ViewModel/Block/Html/Header/LogoPathResolverTest.php
  app/code/Magento/Theme/ViewModel/Block/Html/Header/LogoPathResolver.php
Labels: Progress: accept, partners-contribution, Priority: P2, Partner: Perspective Studio, Project: Community Picked

#34872 Add Cart Rule product subselect total incl. tax option
  app/code/Magento/SalesRule/Model/Rule/Condition/Product/Subselect.php
  app/code/Magento/SalesRule/Test/Unit/Model/Rule/Condition/Product/SubselectTest.php
  app/code/Magento/SalesRule/i18n/en_US.csv
Labels: Progress: accept, Component: SalesRule, Release Line: 2.4, Priority: P3, QA: Added to Regression Scope, Project: Community Picked

#32354 Fix file upload styles duplication in luma theme
  app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/checkout/fields/_file-uploader.less
Labels: Progress: accept, Area: Design/Frontend, Release Line: 2.4, Auto-Tests: Not Required, Triage: Dev.Experience, Priority: P3, Project: Community Picked

#31359 Replace JSON serializer with JSON Hex Tag (User module)
  app/code/Magento/User/ViewModel/JsonSerializer.php
Labels: Progress: accept, partners-contribution, Award: bug fix, Component: User, Release Line: 2.4, Priority: P3, Severity: S3, Partner: Blue Acorn iCi, Project: Community Picked
