Repository magento/magento2, pull requests merged in 2024-07, with the labels that each got.

#38277 V1/customers/password endpoint security
  app/code/Magento/Security/Model/Plugin/AccountManagement.php
  app/code/Magento/Security/Test/Unit/Model/Plugin/AccountManagementTest.php
Labels: Progress: review, Priority: P1

#32511 [Checkout] Depend directives updated in failed payment email template
  app/code/Magento/Checkout/view/adminhtml/email/failed_payment.html
Labels: Progress: accept, Component: Checkout, Area: Frontend, partners-contribution, Award: bug fix, Release Line: 2.4, Auto-Tests: Not Required, Priority: P3, Severity: S3, Priority: P4, Project: Community Picked, Partner: ITG Commerce

#37457 Fix HTML syntax error in visual.phtml
  app/code/Magento/Swatches/view/adminhtml/templates/catalog/product/attribute/visual.phtml
Labels: Award: bug fix, Progress: extended testing, Auto-Tests: Not Required, Priority: P2

#37852 Fix wording of filter item on layered navigation
  app/code/Magento/LayeredNavigation/view/frontend/templates/layer/filter.phtml
Labels: Progress: accept, Priority: P3, Project: Community Picked

#38320 Display backordered quantity if the order item has them
  app/code/Magento/Sales/view/adminhtml/templates/items/column/qty.phtml
Labels: Progress: accept, Priority: P2, Project: Community Picked

#28796 Add unique key on eav_attribute_option_value table
  app/code/Magento/Eav/etc/db_schema.xml
  app/code/Magento/Eav/etc/db_schema_whitelist.json
Labels: Progress: accept, Component: Eav, Release Line: 2.4, Auto-Tests: Not Required, Priority: P2, Severity: S3, Risk: low

#36171 Updated subscriber spelling
  app/code/Magento/Catalog/view/frontend/web/js/product/storage/storage-service.js
Labels: Progress: accept, Cleanup, Auto-Tests: Not Required, Priority: P3

#37349 Fix issue #37348: Google GTag add ecommerce data fix.
  app/code/Magento/GoogleGtag/Block/Ga.php
  app/code/Magento/GoogleGtag/README.md
  app/code/Magento/GoogleGtag/Test/Unit/Block/GaTest.php
  app/code/Magento/GoogleGtag/view/frontend/web/js/google-analytics.js
Labels: Progress: accept, Priority: P2, Project: Community Picked

#38693 Remove jobs no longer referenced in the codebase
  app/code/Magento/Cron/Cron/CleanOldJobs.php
  app/code/Magento/Cron/Test/Unit/Cron/CleanOldJobsTest.php
  app/code/Magento/Cron/composer.json
  app/code/Magento/Cron/etc/crontab.xml
  app/code/Magento/Cron/etc/module.xml
Labels: Progress: accept, partners-contribution, Partner: Youwe, Priority: P2, Project: Community Picked

#36943 Add translatable text in address renderers
  app/code/Magento/Checkout/i18n/en_US.csv
  app/code/Magento/Checkout/view/frontend/web/template/billing-address/details.html
  app/code/Magento/Checkout/view/frontend/web/template/shipping-address/address-renderer/default.html
  app/code/Magento/Checkout/view/frontend/web/template/shipping-information/address-renderer/default.html
  app/code/Magento/Customer/i18n/en_US.csv
  app/code/Magento/Customer/view/adminhtml/web/template/default-address.html
Labels: Progress: accept, Component: Customer, Component: Checkout, partners-contribution, Partner: PHPro, Priority: P3, QA: Added to Regression Scope, Risk: low

#37003 Remove forbidden `@author` tag
  app/code/Magento/Email/Block/Adminhtml/Template.php
  app/code/Magento/Email/Block/Adminhtml/Template/Edit.php
  app/code/Magento/Email/Block/Adminhtml/Template/Grid/Filter/Type.php
  app/code/Magento/Email/Block/Adminhtml/Template/Grid/Renderer/Action.php
  app/code/Magento/Email/Block/Adminhtml/Template/Grid/Renderer/Sender.php
  app/code/Magento/Email/Block/Adminhtml/Template/Grid/Renderer/Type.php
  app/code/Magento/Email/Controller/Adminhtml/Email/Template.php
  app/code/Magento/Email/Model/AbstractTemplate.php
  app/code/Magento/Fedex/Model/Source/Freemethod.php
  app/code/Magento/Fedex/Model/Source/Method.php
  app/code/Magento/Fedex/Model/Source/Packaging.php
  app/code/Magento/GroupedProduct/Block/Product/Grouped/AssociatedProducts/ListAssociatedProducts.php
  app/code/Magento/GroupedProduct/Model/ResourceModel/Indexer/Stock/Grouped.php
  app/code/Magento/GroupedProduct/Model/Sales/AdminOrder/Product/Quote/Plugin/Initializer.php
  app/code/Magento/Integration/Model/Oauth/Consumer.php
  app/code/Magento/Integration/Model/Oauth/Nonce.php
  app/code/Magento/Integration/Model/ResourceModel/Oauth/Nonce.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#36205 Rename wrongly named variable
  app/code/Magento/Sales/Model/Order.php
Labels: Progress: accept, Triage: Dev.Experience, Priority: P2

#37000 Remove forbidden `@author` tag from `Magento_Customer` (part 2)
  app/code/Magento/Customer/Model/Attribute/Data/Multiline.php
  app/code/Magento/Customer/Model/Attribute/Data/Multiselect.php
  app/code/Magento/Customer/Model/Attribute/Data/Select.php
  app/code/Magento/Customer/Model/Attribute/Data/Text.php
  app/code/Magento/Customer/Model/Attribute/Data/Textarea.php
  app/code/Magento/Customer/Model/Config/Backend/Password/Link/Expirationperiod.php
  app/code/Magento/Customer/Model/Config/Backend/Show/Address.php
  app/code/Magento/Customer/Model/Config/Backend/Show/AddressOnly.php
  app/code/Magento/Customer/Model/Config/Backend/Show/Customer.php
  app/code/Magento/Customer/Model/Config/Share.php
  app/code/Magento/Customer/Model/Config/Source/Address/Type.php
  app/code/Magento/Customer/Model/Customer/Attribute/Backend/Billing.php
  app/code/Magento/Customer/Model/Customer/Attribute/Backend/Shipping.php
  app/code/Magento/Customer/Model/Customer/Attribute/Backend/Store.php
  app/code/Magento/Customer/Model/Customer/Attribute/Backend/Website.php
  app/code/Magento/Customer/Model/Customer/Attribute/Source/Group.php
  app/code/Magento/Customer/Model/Customer/Attribute/Source/Store.php
  app/code/Magento/Customer/Model/Customer/Attribute/Source/Website.php
  app/code/Magento/Customer/Model/Form.php
  app/code/Magento/Customer/Model/Renderer/Region.php
  app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Backend/Region.php
  app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Collection.php
  app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Source/Country.php
  app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Source/CountryWithWebsites.php
  app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Source/Region.php
  app/code/Magento/Customer/Model/ResourceModel/Address/Collection.php
  app/code/Magento/Customer/Model/ResourceModel/Attribute.php
  app/code/Magento/Customer/Model/ResourceModel/Attribute/Collection.php
  app/code/Magento/Customer/Model/ResourceModel/Customer/Collection.php
  app/code/Magento/Customer/Model/ResourceModel/Form/Attribute.php
  app/code/Magento/Customer/Model/ResourceModel/Form/Attribute/Collection.php
  app/code/Magento/Customer/Model/ResourceModel/Group.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#38819 Fix shipping rates used to determine instant purchase cheapest shipping
  app/code/Magento/InstantPurchase/Model/QuoteManagement/QuoteCreation.php
  app/code/Magento/InstantPurchase/Model/ShippingMethodChoose/CheapestMethodDeferredChooser.php
Labels: Progress: pending review, Priority: P2, Priority: P1

#37717 Product Media Gallery GQL response is sorted by image position
  app/code/Magento/Catalog/Model/Product/Gallery/ReadHandler.php
Labels: partners-contribution, Partner: EY, Progress: pending review, Priority: P2
