Repository magento/magento2, pull requests merged in 2024-09, with the labels that each got.

#38729 Support connection retries for Redis session and compatible with colinmollenhour/php-redis-session-abstract v2.0.0
  composer.json
  composer.lock
  lib/internal/Magento/Framework/Session/SaveHandler/Redis/Config.php
  lib/internal/Magento/Framework/Session/Test/Unit/SaveHandler/Redis/ConfigTest.php
  lib/internal/Magento/Framework/composer.json
  setup/src/Magento/Setup/Model/ConfigOptionsList/Session.php
  setup/src/Magento/Setup/Test/Unit/Model/ConfigOptionsList/SessionTest.php
Labels: Progress: on hold, Priority: P2, Priority: P1, Priority: P0, Project: Community Picked

#29954 Use compiled config for generated data instead of general config
  app/code/Magento/Ui/etc/di.xml
  app/etc/di.xml
Labels: Progress: accept, Component: Ui, Release Line: 2.4, Triage: Dev.Experience, Priority: P3, Severity: S3, Area: Perf/Frontend, Risk: medium, Project: Community Picked

#33414 Fixed typo in tracking.phtml - renamed JS-functions "currier" to "carrier"
  app/code/Magento/Shipping/view/adminhtml/templates/order/tracking.phtml
Labels: Progress: accept, Area: Frontend, Component: Shipping, Award: bug fix, Cleanup, Release Line: 2.4, Auto-Tests: Not Required, Severity: S4, Priority: P4, Risk: low

#36104 Issue 36101: Category selection tree in edit product is not in the sa…
  app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/CategoriesTest.php
  app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Categories.php
Labels: Progress: accept, Component: Catalog, Priority: P3

#37784 Fixes incorrect classes being referenced in Magento modules.
  app/code/Magento/Catalog/Model/ProductRepository.php
  app/code/Magento/CatalogInventory/Model/Indexer/Stock/Action/Full.php
  app/code/Magento/CatalogRule/Model/ResourceModel/Rule.php
  app/code/Magento/CatalogRule/Model/ResourceModel/Rule/Collection.php
  app/code/Magento/Cms/Model/PageRepository.php
  app/code/Magento/Paypal/Observer/AddPaypalShortcutsObserver.php
  app/code/Magento/Sales/Controller/Adminhtml/Creditmemo/AbstractCreditmemo/PrintAction.php
  app/code/Magento/Sales/Test/Unit/Helper/ReorderTest.php
  app/code/Magento/SalesRule/Model/ResourceModel/Rule.php
  app/code/Magento/SalesRule/Model/ResourceModel/Rule/Collection.php
Labels: Progress: accept, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#38046 Correct typo and grammar in acl.xsd file
  lib/internal/Magento/Framework/Acl/etc/acl.xsd
Labels: Progress: ready for testing, Priority: P3

#38840 Remove 'pub/' directory from paths in css source maps when compiling using grunt
  dev/tools/grunt/configs/less.js
Labels: Progress: accept, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#38842 Fix issue when compiling statics with multiple jobs
  lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php
Labels: Progress: ready for testing, Priority: P3, Project: Community Picked

#38922 magento/magento2#38845:"Area code not set" after update to 2.4.5-p8
  lib/internal/Magento/Framework/App/Area.php
Labels: Progress: accept, partners-contribution, Priority: P2, Project: Community Picked, Partner: Perspective Team

#38925 magento/magento2#32990: Date and Time Format for Custom Option Not Working
  app/code/Magento/Catalog/Block/Product/View/Options/Type/Date.php
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminAddCustomizableOptionToSimpleProductActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminConfigExpandDateAndTimeTabActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AssertProductDateFormatInStorefrontActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/SelectDropdownDateAndTimeActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/Section/AdminCustomizeDateAndTimeSection.xml
  app/code/Magento/Catalog/Test/Mftf/Section/AdminProductCustomizableOptionSection.xml
  app/code/Magento/Catalog/Test/Mftf/Section/StorefrontProductInfoMainSection.xml
  app/code/Magento/Catalog/Test/Mftf/Test/AdminJsCalenderDateFormatTest.xml
  app/code/Magento/Config/Test/Mftf/Section/CatalogSection/CatalogSection.xml
Labels: Progress: accept, partners-contribution, Priority: P3, Project: Community Picked, Partner: Perspective Team

#38926 magento#38805: Issue at product import when provided with custom options-type: file
  app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
  app/code/Magento/CatalogImportExport/Test/Unit/Model/Import/Product/Type/OptionTest.php
Labels: Progress: accept, partners-contribution, Priority: P2, Project: Community Picked, Partner: Perspective Team

#38951 Remove references to files from extjs which got removed in e1ccdb…
  app/code/Magento/Backend/view/adminhtml/layout/default.xml
  app/code/Magento/Email/view/adminhtml/layout/adminhtml_email_template_preview.xml
  app/code/Magento/Theme/view/adminhtml/requirejs-config.js
  app/code/Magento/Widget/view/adminhtml/templates/catalog/category/widget/tree.phtml
  dev/tests/static/testsuite/Magento/Test/Js/_files/whitelist/magento.txt
Labels: Progress: accept, Priority: P1, Project: Community Picked

#38663 38662 - Graphql type error fix
  app/code/Magento/CustomerGraphQl/Model/Customer/GetCustomSelectedOptionAttributes.php
Labels: Progress: ready for testing, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#38713 fix-page-action-float-issue
  app/design/adminhtml/Magento/backend/Magento_Backend/web/css/source/module/main/_actions-bar.less
Labels: Progress: pending review, Priority: P2

#37842 [WIP] Updated wikimedia/less.php from v3 to v5
  app/design/frontend/Magento/blank/web/css/source/_extends.less
  app/design/frontend/Magento/luma/web/css/source/_extends.less
  composer.json
  composer.lock
  lib/internal/Magento/Framework/composer.json
Labels: Area: Design/Frontend, Progress: review, Priority: P2
