Repository magento/magento2, pull requests merged in 2024-10, with the labels that each got.

#30070 Pass custom attributes to current link via XML
  lib/internal/Magento/Framework/View/Element/Html/Link/Current.php
Labels: Progress: ready for testing, Component: View, Release Line: 2.4, Triage: Dev.Experience, Priority: P3, Severity: S3, Risk: medium, Project: Community Picked

#34643 Remove unnecessary scripts review summary
  app/code/Magento/Review/view/frontend/templates/helper/summary.phtml
  app/code/Magento/Review/view/frontend/templates/helper/summary_short.phtml
  app/code/Magento/Review/view/frontend/templates/product/view/list.phtml
  app/code/Magento/Review/view/frontend/templates/view.phtml
Labels: Area: Frontend, Component: Review, Progress: ready for testing, Release Line: 2.4, Priority: P3, Project: Community Picked

#38279 add permission check for "reload data" data button
  app/code/Magento/Backend/view/adminhtml/templates/dashboard/totalbar/refreshstatistics.phtml
Labels: Progress: ready for testing, Priority: P2, Project: Community Picked

#38759 Ability to define Area for dev:di:info CLI command #38758
  app/code/Magento/Developer/Console/Command/DiInfoCommand.php
  dev/tests/integration/testsuite/Magento/Developer/Console/Command/DiInfoCommandTest.php
Labels: partners-contribution, Progress: ready for testing, Priority: P3, Priority: P1, Project: Community Picked, Partner: Perspective Team

#39040 AC-12731 Issue#39020 Rendering the critical css inline event via csp …
  app/code/Magento/Theme/Controller/Result/AsyncCssPlugin.php
  app/code/Magento/Theme/Test/Unit/Controller/Result/AsyncCssPluginTest.php
  app/code/Magento/Theme/composer.json
  app/code/Magento/Theme/etc/module.xml
Labels: partners-contribution, Progress: ready for testing, Partner: Ziffity, Priority: P2, Project: Community Picked

#39084 Add FTP to composer.json
  composer.json
  lib/internal/Magento/Framework/composer.json
Labels: partners-contribution, Progress: ready for testing, Triage: Dev.Experience, Partner: Le Site, Priority: P1, Project: Community Picked

#35174 Set default collation to utf8mb4
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/fixture/declarative_installer/constraint_modification.mariadb10611.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/fixture/declarative_installer/constraint_modification.mysql829.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/fixture/declarative_installer/rollback.mariadb10611.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/fixture/declarative_installer/rollback.mysql829.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/fixture/declarative_installer/table_removal.mariadb10611.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/fixture/declarative_installer/table_removal.mysql829.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/fixture/declarative_installer/table_rename.mariadb10611.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/fixture/declarative_installer/table_rename.mysql829.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/fixture/dry_run_log.mariadb10611.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/fixture/dry_run_log.mysql829.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/revisions/base_update/InstallSchema.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/revisions/old_diff/InstallSchema.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule2/fixture/shards.mariadb10611.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule2/fixture/shards.mysql829.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule9/fixture/declarative_installer/disabling_tables.mariadb10611.php
  dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule9/fixture/declarative_installer/disabling_tables.mysql829.php
  lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Factories/Table.php
Labels: Progress: needs update, Component: Setup, partners-contribution, Partner: TechDivision, Release Line: 2.4, Triage: Dev.Experience, Priority: P3, Issue: needs update, Project: Community Picked
