Repository magento/magento2, pull requests merged in 2024-05, with the labels that each got.

#38439 Fix PHPDocs for \Magento\Framework\Data\Collection::getItemById
  app/code/Magento/Eav/Test/Unit/Model/Entity/Collection/AbstractCollectionStub.php
  app/code/Magento/Eav/Test/Unit/Model/Entity/Collection/VersionControl/AbstractCollectionStub.php
  lib/internal/Magento/Framework/Data/Collection.php
Labels: Progress: accept, Cleanup, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#38248 Added support for process fork to mview indexation
  lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalker.php
Labels: Progress: accept, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#38364 Fixes problem with latest versions of ICU library where AmPmMarkers i…
  lib/internal/Magento/Framework/View/Element/Html/Calendar.php
  lib/internal/Magento/Framework/View/Test/Unit/Element/Html/CalendarTest.php
Labels: Progress: accept, Award: category of expertise, Triage: Dev.Experience, Priority: P1, Project: Community Picked

#38410 Changed "active" to "enabled" in bin/magento maintenance:status command
  app/code/Magento/Backend/Console/Command/MaintenanceStatusCommand.php
  app/code/Magento/Backend/Test/Unit/Console/Command/MaintenanceStatusCommandTest.php
Labels: Progress: accept, Auto-Tests: Covered, Priority: P3, Project: Community Picked

#38427 Fixed tier price issue on configurable product
  app/code/Magento/ConfigurableProduct/Plugin/Catalog/Model/Product/Attribute/Backend/TierPrice/UpdateHandlerPlugin.php
  app/code/Magento/ConfigurableProduct/Test/Unit/Plugin/Catalog/Model/Product/Attribute/Backend/TierPrice/UpdateHandlerPluginTest.php
  app/code/Magento/ConfigurableProduct/etc/di.xml
Labels: Progress: accept, Priority: P2, Project: Community Picked

#38447 Fixed special characters issue on product name
  app/code/Magento/Catalog/Test/Mftf/Data/ProductData.xml
  app/code/Magento/ConfigurableProduct/Test/Mftf/Test/AdminConfigurableProductWithSpecialCharacterNameTest.xml
  app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Form/Modifier/Data/AssociatedProducts.php
Labels: Progress: accept, Priority: P3, Project: Community Picked

#38449 Fix issues with Customer Data when form contains element with name `method`
  app/code/Magento/Catalog/view/frontend/web/js/storage-manager.js
  app/code/Magento/Customer/view/frontend/web/js/customer-data.js
Labels: Progress: accept, Triage: Dev.Experience, Priority: P1, Project: Community Picked

#37199 Use visibility class for category product indexer, instead of hardcoded values
  app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php
Labels: Progress: accept, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#37932 Wrong store ID used in Order Address Renderer
  app/code/Magento/Sales/Model/Order/Address/Renderer.php
  app/code/Magento/Sales/Test/Unit/Model/Order/Address/RendererTest.php
  dev/tests/integration/testsuite/Magento/Sales/Model/Order/Address/RendererTest.php
Labels: Progress: accept, partners-contribution, Triage: Dev.Experience, Priority: P2, Project: Community Picked, Partner: Dn’D

#38050 Mitigate performance issue in #36667 during price indexing
  app/code/Magento/CatalogInventory/Model/Plugin/ProductLinks.php
  app/code/Magento/CatalogInventory/Test/Unit/Model/Plugin/ProductLinksTest.php
Labels: Progress: accept, Triage: Dev.Experience, Priority: P2, Area: Performance, Project: Community Picked

#36949 Adding created_at, status and grand_total filters to customer Orders query and fixing multiple filters failure
  app/code/Magento/SalesGraphQl/Model/Resolver/CustomerOrders/Query/OrderFilter.php
  app/code/Magento/SalesGraphQl/etc/schema.graphqls
Labels: Progress: accept, Priority: P2

#36368 Do not load backend block context on frontend
  app/code/Magento/GiftMessage/Block/Cart/GiftOptions.php
  app/code/Magento/GiftMessage/Block/Cart/Item/Renderer/Actions/GiftOptions.php
Labels: Progress: accept, Priority: P2, Area: Performance, Project: Community Picked

#30699 Allow use of CIDR ranges in maintenance allow list
  app/code/Magento/Backend/Model/Validator/IpValidator.php
  app/code/Magento/Backend/Test/Unit/Model/Validator/IpValidatorTest.php
  lib/internal/Magento/Framework/App/MaintenanceMode.php
  lib/internal/Magento/Framework/App/Test/Unit/MaintenanceModeTest.php
  lib/internal/Magento/Framework/App/Utility/IPAddress.php
Labels: Progress: accept, Award: test coverage, partners-contribution, Award: bug fix, Component: Backend, Component: Composer, Component: App, Release Line: 2.4, Partner: Fisheye, Auto-Tests: Covered, Priority: P3, Severity: S4, Project: Community Picked

#30838 [MFTF] Added AdminClickAddOptionForBundleItemsActionGroup
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AdminClickAddOptionForBundleItemsActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminAddBundleItemsTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminAddDefaultImageBundleProductTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminDeleteABundleProductTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminFilterProductListByBundleProductTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminMassDeleteBundleProductsTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminRemoveDefaultImageBundleProductTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/BundleProductFixedPricingTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/EnableDisableBundleProductStatusTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/EndToEndB2CAdminTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/MassEnableDisableBundleProductsTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/NewProductsListWidgetBundleProductTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/StorefrontAdminEditDataTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/StorefrontBundleProductDetailsTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/StorefrontBundleProductShownInCategoryListAndGridTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/StorefrontEditBundleProductTest.xml
  app/code/Magento/Bundle/Test/Mftf/Test/StorefrontGoToDetailsPageWhenAddingToCartTest.xml
Labels: Progress: accept, partners-contribution, Partner: Atwix, Component: Bundle, Release Line: 2.4, Auto-Tests: Covered, Priority: P3, Severity: S3

#25859 Drop indexer changelog tables on mview unsubscribe
  app/code/Magento/Indexer/Model/Indexer.php
  app/code/Magento/Indexer/Setup/Recurring.php
  app/code/Magento/Indexer/Test/Unit/Model/IndexerTest.php
  lib/internal/Magento/Framework/Mview/Test/Unit/ViewSubscribeTest.php
  lib/internal/Magento/Framework/Mview/View.php
  lib/internal/Magento/Framework/Mview/ViewInterface.php
Labels: Progress: accept, partners-contribution, Component: Indexer, Component: Mview, Release Line: 2.4, Partner: Fisheye, Auto-Tests: Covered, Priority: P3, Severity: S3, QA: Added to Regression Scope, Risk: high, Project: Community Picked

#38407 Fix issue 38406
  app/code/Magento/Customer/Block/Address/Edit.php
Labels: Progress: accept, Priority: P2

#37899 fix currency in new widget
  app/code/Magento/Catalog/Block/Product/Widget/NewWidget.php
  dev/tests/integration/testsuite/Magento/Catalog/Block/Product/NewTest.php
Labels: Progress: accept, Award: test coverage, Priority: P2

#36263 Issue 35838: Customer is logged in but showing 404 error in frontend.
  app/code/Magento/Customer/Model/Url.php
  app/code/Magento/Customer/Test/Unit/Model/UrlTest.php
Labels: Progress: accept, Component: Customer, Priority: P3
