Repository magento/magento2, pull requests merged in 2024-11, with the labels that each got.

#36394 Use current sore id for category runtime cache
  app/code/Magento/Catalog/Model/CategoryRepository.php
  app/code/Magento/Catalog/Model/ResourceModel/Category.php
  dev/tests/integration/testsuite/Magento/Catalog/Controller/Adminhtml/Category/Save/UpdateCategoryTest.php
  dev/tests/integration/testsuite/Magento/Catalog/Controller/Adminhtml/CategoryTest.php
  dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/CategoryUrlPathAutogeneratorObserverTest.php
Labels: Progress: ready for testing, Triage: Dev.Experience, Priority: P2, Priority: P3, Severity: S3, Project: Community Picked

#38539 Redirect loop when URL have uppercase
  app/code/Magento/Config/Model/Config/Backend/Baseurl.php
  app/code/Magento/Config/Test/Unit/Model/Config/Backend/BaseurlTest.php
Labels: Progress: review, Priority: P3, Project: Community Picked

#38996 Fix Warning: Undefined array key "filters"
  app/code/Magento/Ui/Controller/Adminhtml/Bookmark/Save.php
Labels: partners-contribution, Progress: ready for testing, Priority: P2, Project: Community Picked, Partner: Dn’D

#39188 Add Tracking Parameters to Varnish Configuration
  app/code/Magento/PageCache/etc/varnish4.vcl
  app/code/Magento/PageCache/etc/varnish5.vcl
  app/code/Magento/PageCache/etc/varnish6.vcl
  app/code/Magento/PageCache/etc/varnish7.vcl
Labels: Progress: ready for testing, Priority: P2, Project: Community Picked

#33161 Allow only valid preferences during setup:di:compile
  app/code/Magento/Catalog/etc/di.xml
  app/code/Magento/RemoteStorage/etc/di.xml
  app/etc/di.xml
  dev/tests/static/testsuite/Magento/Test/Legacy/_files/obsolete_classes.php
  setup/src/Magento/Setup/Console/Command/DiCompileCommand.php
  setup/src/Magento/Setup/Module/Di/Code/Reader/Decorator/Area.php
  setup/src/Magento/Setup/Module/Di/Compiler/ArgumentsResolver.php
  setup/src/Magento/Setup/Module/Di/Compiler/Config/Reader.php
  setup/src/Magento/Setup/Module/Di/Definition/Collection.php
  setup/src/Magento/Setup/Test/Unit/Module/Di/Compiler/Config/ReaderTest.php
Labels: Component: Setup, Progress: on hold, partners-contribution, Release Line: 2.4, Partner: Fisheye, Partner: Youwe, Triage: Dev.Experience, Priority: P3, Project: Community Picked

#38991 issue 37750: whitelisting *.google-analytics.com *.analytics.google.com
  app/code/Magento/GoogleGtag/etc/csp_whitelist.xml
Labels: Progress: ready for testing, Priority: P2, Project: Community Picked

#39202 Removes some code for PHP versions we no longer support.
  lib/internal/Magento/Framework/Webapi/Rest/Request/Deserializer/Xml.php
  lib/internal/Magento/Framework/Xml/Security.php
  setup/src/Magento/Setup/Model/PhpReadinessCheck.php
  setup/src/Magento/Setup/Test/Unit/Model/PhpReadinessCheckTest.php
Labels: Progress: ready for testing, Triage: Dev.Experience, Priority: P2, Project: Community Picked

#39241 [PHPDOC] Fix bad phpdoc Magento\Directory\Model\AllowedCountries::getAllowedCountries()
  app/code/Magento/Directory/Model/AllowedCountries.php
Labels: Progress: ready for testing, Triage: Dev.Experience, Priority: P3, Project: Community Picked
