Repository magento/magento2, pull requests merged in 2025-08, with the labels that each got.

#37933 Resolved 37820 console error in email preview
  app/code/Magento/Email/view/adminhtml/templates/preview/iframeswitcher.phtml
Labels: Component: Email, Priority: P2, Project: Community Picked

#38239 Fix Patch aliases usage (issue #31396)
  lib/internal/Magento/Framework/Setup/Patch/PatchApplier.php
  lib/internal/Magento/Framework/Setup/Test/Unit/Patch/PatchApplierTest.php
Labels: Triage: Dev.Experience, Priority: P3, Severity: S3, Project: Community Picked

#38617 Accessibility: WAI-ARIA roles nesting wrong in menu
  app/code/Magento/Theme/Block/Html/Topmenu.php
  app/code/Magento/Theme/Test/Unit/Block/Html/TopmenuTest.php
  dev/tests/static/testsuite/Magento/Test/Integrity/App/Language/_files/known_invalid.xml
  dev/tests/static/testsuite/Magento/Test/Integrity/App/Language/_files/known_valid.xml
Labels: Priority: P2, Project: Community Picked

#39888 magento/magento2#39729: Cannot return null for non-nullable field "SelectedCustomizableOption.label"
  app/code/Magento/QuoteGraphQl/Model/Resolver/CustomizableOptions.php
  app/code/Magento/QuoteGraphQl/Test/Unit/Model/Resolver/CustomizableOptionsTest.php
Labels: partners-contribution, Priority: P2, Partner: Perspective, Project: Community Picked

#40033 Remove sprintf usage in phrase calls
  app/code/Magento/Catalog/Model/FrontendStorageConfigurationPool.php
  app/code/Magento/CatalogInventory/Model/StockStateProvider.php
  app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php
  app/code/Magento/EavGraphQl/Model/GetAttributeSelectedOptionComposite.php
  app/code/Magento/EavGraphQl/Model/GetAttributeValueComposite.php
  app/code/Magento/SalesRule/Model/Coupon/Usage/Processor.php
  app/code/Magento/Store/Model/WebsiteRepository.php
  dev/tests/integration/testsuite/Magento/Catalog/Controller/Adminhtml/Category/DeleteTest.php
  dev/tests/integration/testsuite/Magento/Catalog/Model/Product/Attribute/Save/AbstractAttributeTest.php
  dev/tests/integration/testsuite/Magento/UrlRewrite/Controller/Adminhtml/SaveRewriteTest.php
Labels: Triage: Dev.Experience, Priority: P2, Project: Community Picked

#32451 Add EventPrefix and EventObject to checkout agreement model
  app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js
Labels: Component: CheckoutAgreements, Progress: ready for testing, Release Line: 2.4, Auto-Tests: Covered, Triage: Dev.Experience, Priority: P3

#33470 Fix validate-emails rule for ui component
  app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js
Labels: Area: Frontend, Component: Ui, Cleanup, Progress: ready for testing, Release Line: 2.4, Triage: Dev.Experience, Priority: P3

#36979 Remove forbidden `@author` tag from `Magento_Backup` and `Magento_Bundle`
  app/code/Magento/Backup/Block/Adminhtml/Backup.php
  app/code/Magento/Backup/Block/Adminhtml/Grid/Column/Renderer/Download.php
  app/code/Magento/Backup/Block/Adminhtml/Grid/Column/Rollback.php
  app/code/Magento/Backup/Controller/Adminhtml/Index.php
  app/code/Magento/Backup/Model/Config/Source/Type.php
  app/code/Magento/Backup/Model/Grid/Options.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Composite/Fieldset/Options/Type/Checkbox.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Composite/Fieldset/Options/Type/Multi.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Composite/Fieldset/Options/Type/Radio.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Composite/Fieldset/Options/Type/Select.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tab/Attributes/Extend.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tab/Attributes/Special.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tab/Bundle.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tab/Bundle/Option/Search.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tab/Bundle/Option/Search/Grid.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tab/Bundle/Option/Selection.php
  app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tabs.php
  app/code/Magento/Bundle/Helper/Data.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#37009 Remove forbidden `@author` tag
  app/code/Magento/Reports/Block/Adminhtml/Sales/Refunded.php
  app/code/Magento/Reports/Block/Adminhtml/Sales/Refunded/Grid.php
  app/code/Magento/Reports/Block/Adminhtml/Sales/Sales.php
  app/code/Magento/Reports/Block/Adminhtml/Sales/Shipping.php
  app/code/Magento/Reports/Block/Adminhtml/Sales/Shipping/Grid.php
  app/code/Magento/Reports/Block/Adminhtml/Sales/Tax.php
  app/code/Magento/Reports/Block/Adminhtml/Sales/Tax/Grid.php
  app/code/Magento/Reports/Block/Adminhtml/Shopcart/Abandoned.php
  app/code/Magento/Reports/Block/Adminhtml/Shopcart/Abandoned/Grid.php
  app/code/Magento/Reports/Block/Adminhtml/Shopcart/Customer.php
  app/code/Magento/Reports/Block/Adminhtml/Shopcart/Customer/Grid.php
  app/code/Magento/Reports/Block/Adminhtml/Shopcart/Product.php
  app/code/Magento/Reports/Block/Adminhtml/Wishlist.php
  app/code/Magento/Reports/Block/Adminhtml/Wishlist/Grid.php
  app/code/Magento/Reports/Block/Product/AbstractProduct.php
  app/code/Magento/Reports/Block/Product/Compared.php
  app/code/Magento/Reports/Block/Product/Viewed.php
  app/code/Magento/Reports/Block/Product/Widget/Viewed/Item.php
  app/code/Magento/Reports/Controller/Adminhtml/Index.php
  app/code/Magento/Reports/Controller/Adminhtml/Report/AbstractReport.php
  app/code/Magento/Reports/Controller/Adminhtml/Report/Customer.php
  app/code/Magento/Reports/Controller/Adminhtml/Report/Product.php
  app/code/Magento/Reports/Controller/Adminhtml/Report/Review.php
  app/code/Magento/Reports/Controller/Adminhtml/Report/Sales.php
  app/code/Magento/Reports/Controller/Adminhtml/Report/Shopcart.php
  app/code/Magento/Reports/Model/Event.php
  app/code/Magento/Reports/Model/Flag.php
  app/code/Magento/Reports/Model/Product/Index/Compared.php
  app/code/Magento/Reports/Model/Product/Index/Viewed.php
  app/code/Magento/Reports/Model/ResourceModel/Accounts/Collection.php
  app/code/Magento/Reports/Model/ResourceModel/Accounts/Collection/Initial.php
  app/code/Magento/Reports/Model/ResourceModel/Customer/Orders/Collection.php
  app/code/Magento/Reports/Model/ResourceModel/Customer/Orders/Collection/Initial.php
  app/code/Magento/Reports/Model/ResourceModel/Customer/Totals/Collection.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#37012 Remove forbidden `@author` tag
  app/code/Magento/Sales/Block/Adminhtml/Order/Create/Totals/Discount.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Create/Totals/Grandtotal.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Create/Totals/Shipping.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Create/Totals/Subtotal.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Create/Totals/Table.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Create/Totals/Tax.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Creditmemo/Totals.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Creditmemo/View.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Creditmemo/View/Comments.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Creditmemo/View/Form.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Invoice/Create/Form.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Invoice/Totals.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Invoice/View.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Invoice/View/Comments.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Invoice/View/Form.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Payment.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Status.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Totalbar.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Totals.php
  app/code/Magento/Sales/Block/Adminhtml/Order/Totals/Tax.php
  app/code/Magento/Sales/Block/Adminhtml/Order/View/Form.php
  app/code/Magento/Sales/Block/Adminhtml/Order/View/Giftmessage.php
  app/code/Magento/Sales/Block/Adminhtml/Order/View/Messages.php
  app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Info.php
  app/code/Magento/Sales/Block/Adminhtml/Reorder/Renderer/Action.php
  app/code/Magento/Sales/Block/Adminhtml/Report/Filter/Form.php
  app/code/Magento/Sales/Block/Adminhtml/Report/Filter/Form/Coupon.php
  app/code/Magento/Sales/Block/Adminhtml/Report/Filter/Form/Order.php
  app/code/Magento/Sales/Block/Adminhtml/Shipment.php
  app/code/Magento/Sales/Block/Adminhtml/Transactions.php
  app/code/Magento/Sales/Block/Adminhtml/Transactions/Detail.php
  app/code/Magento/Sales/Block/Adminhtml/Transactions/Detail/Grid.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#37015 Remove forbidden `@author` tag
  app/code/Magento/Sales/Model/ResourceModel/Order/Tax.php
  app/code/Magento/Sales/Model/ResourceModel/Order/Tax/Collection.php
  app/code/Magento/Sales/Model/ResourceModel/Report.php
  app/code/Magento/Sales/Model/ResourceModel/Report/AbstractReport.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Collection/AbstractCollection.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Invoiced.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Invoiced/Collection/Invoiced.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Invoiced/Collection/Order.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Order/Collection.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Order/Createdat.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Order/Updatedat.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Order/Updatedat/Collection.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Refunded.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Refunded/Collection/Order.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Refunded/Collection/Refunded.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Shipping.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Shipping/Collection/Order.php
  app/code/Magento/Sales/Model/ResourceModel/Report/Shipping/Collection/Shipment.php
  app/code/Magento/Sales/Model/Status/ListStatus.php
  app/code/Magento/SalesRule/Block/Adminhtml/Promo/Quote.php
  app/code/Magento/SalesRule/Block/Adminhtml/Promo/Quote/Edit/Tab/Coupons.php
  app/code/Magento/SalesRule/Block/Adminhtml/Promo/Quote/Edit/Tab/Coupons/Form.php
  app/code/Magento/SalesRule/Block/Adminhtml/Promo/Quote/Edit/Tab/Coupons/Grid/Column/Renderer/Used.php
  app/code/Magento/SalesRule/Model/Coupon/Massgenerator.php
  app/code/Magento/SalesRule/Model/ResourceModel/Coupon/Collection.php
  app/code/Magento/SalesRule/Model/ResourceModel/Coupon/Usage.php
  app/code/Magento/SalesRule/Model/ResourceModel/Report/Collection.php
  app/code/Magento/SalesRule/Model/ResourceModel/Report/Rule.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#37016 Remove forbidden `@author` tag
  app/code/Magento/SalesRule/Model/ResourceModel/Report/Rule/Updatedat.php
  app/code/Magento/SalesRule/Model/ResourceModel/Report/Updatedat/Collection.php
  app/code/Magento/SalesRule/Model/ResourceModel/Rule/Customer.php
  app/code/Magento/SalesRule/Model/ResourceModel/Rule/Customer/Collection.php
  app/code/Magento/SalesRule/Model/Rule/Customer.php
  app/code/Magento/SalesRule/Model/System/Config/Source/Coupon/Format.php
  app/code/Magento/SendFriend/Block/Send.php
  app/code/Magento/SendFriend/Helper/Data.php
  app/code/Magento/SendFriend/Model/ResourceModel/SendFriend/Collection.php
  app/code/Magento/SendFriend/Model/SendFriend.php
  app/code/Magento/SendFriend/Model/Source/Checktype.php
  app/code/Magento/Shipping/Block/Adminhtml/View.php
  app/code/Magento/Shipping/Block/Adminhtml/View/Comments.php
  app/code/Magento/Shipping/Block/Adminhtml/View/Form.php
  app/code/Magento/Shipping/Block/Items.php
  app/code/Magento/Shipping/Model/Shipment/Request.php
  app/code/Magento/Shipping/Model/Shipment/ReturnShipment.php
  app/code/Magento/Sitemap/Block/Adminhtml/Edit.php
  app/code/Magento/Sitemap/Block/Adminhtml/Edit/Form.php
  app/code/Magento/Sitemap/Model/Observer.php
  app/code/Magento/Sitemap/Model/ResourceModel/Sitemap/Collection.php
Labels: partners-contribution, Partner: Fisheye, Priority: P2

#39971 Error getting order item discounts applied_to for customer order via …
  app/code/Magento/SalesGraphQl/Model/OrderItem/DataProvider.php
Labels: Progress: pending review, Priority: P2

#39972 Error getting order item coupon code for customer order via GraphQl customer request
  app/code/Magento/SalesGraphQl/Model/OrderItem/DataProvider.php
Labels: Progress: pending review, Priority: P2

#33499 Cleaning up unused code.
  app/code/Magento/CatalogInventory/Model/ProductCollectionStockCondition.php
  app/code/Magento/CatalogInventory/Model/ResourceModel/Stock/Item/StockItemCriteria.php
  app/code/Magento/CatalogInventory/Model/ResourceModel/Stock/Status/StockStatusCriteria.php
  app/code/Magento/CatalogInventory/Model/StockRegistry.php
  app/code/Magento/CatalogInventory/Model/StockRegistryProvider.php
  app/code/Magento/CatalogInventory/Setup/Patch/Data/CreateDefaultStock.php
  app/code/Magento/CatalogInventory/Setup/Patch/Data/UpdateStockItemsWebsite.php
Labels: Cleanup, Component: CatalogInventory, Release Line: 2.4, Auto-Tests: Not Required, Triage: Dev.Experience, Severity: S4, Priority: P4, Risk: low, Type: Code Cleanup

#36976 Remove forbidden `@author` tag from `Magento_Backend`
  app/code/Magento/Backend/Block/Dashboard/AbstractDashboard.php
  app/code/Magento/Backend/Block/Dashboard/Bar.php
  app/code/Magento/Backend/Block/Dashboard/Diagrams.php
  app/code/Magento/Backend/Block/Dashboard/Graph.php
  app/code/Magento/Backend/Block/Dashboard/Grid.php
  app/code/Magento/Backend/Block/Dashboard/Grids.php
  app/code/Magento/Backend/Block/Dashboard/Sales.php
  app/code/Magento/Backend/Block/Dashboard/Tab/Amounts.php
  app/code/Magento/Backend/Block/Dashboard/Tab/Orders.php
  app/code/Magento/Backend/Block/Dashboard/Tab/Products/Ordered.php
  app/code/Magento/Backend/Block/Page.php
  app/code/Magento/Backend/Block/Page/Footer.php
  app/code/Magento/Backend/Block/Page/Header.php
  app/code/Magento/Backend/Block/Page/Notices.php
  app/code/Magento/Backend/Block/Page/System/Config/Robots/Reset.php
  app/code/Magento/Backend/Block/System/Account/Edit.php
  app/code/Magento/Backend/Block/System/Account/Edit/Form.php
  app/code/Magento/Backend/Block/System/Cache/Edit.php
  app/code/Magento/Backend/Block/System/Cache/Form.php
  app/code/Magento/Backend/Block/System/Store/Delete.php
  app/code/Magento/Backend/Block/System/Store/Delete/Form.php
  app/code/Magento/Backend/Block/System/Store/Delete/Group.php
  app/code/Magento/Backend/Block/System/Store/Delete/Website.php
  app/code/Magento/Backend/Block/System/Store/Edit/AbstractForm.php
  app/code/Magento/Backend/Block/System/Store/Edit/Form/Group.php
  app/code/Magento/Backend/Block/System/Store/Edit/Form/Store.php
  app/code/Magento/Backend/Block/System/Store/Edit/Form/Website.php
  app/code/Magento/Backend/Block/System/Store/Grid/Render/Group.php
  app/code/Magento/Backend/Block/System/Store/Grid/Render/Store.php
  app/code/Magento/Backend/Block/System/Store/Grid/Render/Website.php
  app/code/Magento/Backend/Block/System/Store/Store.php
  app/code/Magento/Backend/Block/Text/ListText.php
  app/code/Magento/Backend/Block/Widget/Accordion/Item.php
  app/code/Magento/Backend/Block/Widget/Breadcrumbs.php
  app/code/Magento/Backend/Block/Widget/Button.php
  app/code/Magento/Backend/Block/Widget/Form/Element.php
  app/code/Magento/Backend/Block/Widget/Form/Element/Gallery.php
  app/code/Magento/Backend/Block/Widget/Form/Renderer/Fieldset.php
  app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Checkbox.php
  app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Datetime.php
  app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Massaction.php
  app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Price.php
  app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Radio.php
  app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Range.php
  app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/SkipList.php
  app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Text.php
  app/code/Magento/Backend/Block/Widget/Grid/Massaction/Extended.php
  app/code/Magento/Backend/Block/Widget/Grid/Massaction/Item/Additional/AdditionalInterface.php
  app/code/Magento/Backend/Block/Widget/Grid/Massaction/Item/Additional/DefaultAdditional.php
  app/code/Magento/Backend/Controller/Adminhtml/Dashboard.php
  app/code/Magento/Backend/Controller/Adminhtml/System.php
  app/code/Magento/Backend/Controller/Adminhtml/System/Account.php
  app/code/Magento/Backend/Controller/Adminhtml/System/Store.php
  app/code/Magento/Backend/Helper/Js.php
  app/code/Magento/Backend/Model/Auth/Credential/StorageInterface.php
  app/code/Magento/Backend/Model/Locale/Manager.php
  app/code/Magento/Backend/Model/Search/Order.php
Labels: Progress: accept, partners-contribution, Partner: Fisheye, Priority: P2

#38883 Handle errors when the cms page graphql query returns no result
  app/code/Magento/UrlRewriteGraphQl/Model/Resolver/Route.php
Labels: Progress: pending review, Priority: P2
