Repository magento/magento2, pull requests merged in 2025-03, with the labels that each got.

#31231 Inconsistent labels for attributes in marketing rules
  app/code/Magento/SalesRule/Model/Rule/Condition/Product.php
  app/code/Magento/SalesRule/i18n/en_US.csv
Labels: Award: bug fix, Component: SalesRule, Progress: ready for testing, Release Line: 2.4, Auto-Tests: Not Required, Severity: S4, Priority: P4, Project: Community Picked

#39371 magento/magento2#38891: Hidden dropdown in grids with select action (…
  app/design/adminhtml/Magento/backend/Magento_Ui/web/css/source/module/_data-grid.less
Labels: Progress: ready for testing, Priority: P2, Project: Community Picked

#39558 Magento\Framework\Filesystem\Driver\Http::isExists - Removed "OK" phrase check
  lib/internal/Magento/Framework/Filesystem/Driver/Http.php
  lib/internal/Magento/Framework/Filesystem/Test/Unit/Driver/HttpTest.php
Labels: Triage: Dev.Experience, Progress: review, Priority: P2, Project: Community Picked

#39601 Removed the customer logged in condition from reorder method
  app/code/Magento/Sales/Helper/Reorder.php
  app/code/Magento/Sales/Test/Unit/Helper/ReorderTest.php
Labels: partners-contribution, Progress: ready for testing, Partner: Ziffity, Priority: P2, Project: Community Picked
